export  const hierarchy ={ 
    "All grades comperhensive": {
        "Tense":[
            {text:"She ________ to music while she ________ her homework right now.", options:["listens / does", "is listening / is doing", "is listening / does", "listens / is doing"], correct:1},
{text:"The sun ________ in the east. This is a scientific fact.", options:["is rising", "rises", "has risen", "has been rising"], correct:1},
{text:"'I ________ you can do this,' the teacher said during the exam.", options:["am believing", "believe", "have believed", "believed"], correct:1},
{text:"The train ________ at 6:00 AM tomorrow according to the schedule.", options:["will leave", "is leaving", "leaves", "is going to leave"], correct:2},
{text:"She ________ coffee, but she ________ tea this morning because there is no coffee.", options:["hates / is drinking", "is hating / drinks", "is hating / is drinking", "hates / drinks"], correct:0},
{text:"The water ________ at 100°C. [Choose the grammatically correct AND contextually appropriate form]", options:["is boiling", "boils", "has been boiling", "boiled"], correct:1},
{text:"He ________ a new novel these days, so he is very busy.", options:["writes", "has written", "is writing", "wrote"], correct:2},
{text:"I ________ what you mean, but I ________ with your conclusion.", options:["am seeing / am disagreeing", "see / disagree", "see / am disagreeing", "am seeing / disagree"], correct:2},
{text:"The committee ________ on the proposal as we speak.", options:["decides", "has decided", "is deciding", "decided"], correct:2},
{text:"I ________ this perfume. It ________ of roses.", options:["am loving / smells", "love / is smelling", "love / smells", "am loving / is smelling"], correct:2},
{text:"By the time the ambulance arrived, the patient ________.", options:["died", "was dying", "has died", "had died"], correct:3},
{text:"She ________ in Paris for ten years before she moved to London.", options:["lived", "had lived", "was living", "has lived"], correct:1},
{text:"I ________ the film twice, so I knew the ending.", options:["saw", "had seen", "was seeing", "have seen"], correct:1},
{text:"When I entered the room, everyone ________ at me.", options:["looked", "was looking", "had looked", "has been looking"], correct:1},
{text:"He ________ to finish the project all night when the power went out.", options:["tried", "was trying", "had tried", "had been trying"], correct:3},
{text:"My grandfather ________ as a soldier in World War II.", options:["has served", "was serving", "served", "had served"], correct:2},
{text:"Hardly ________ when it started to rain.", options:["we had arrived", "had we arrived", "we arrived", "did we arrive"], correct:1},
{text:"It was the first time I ________ sushi.", options:["ate", "had eaten", "have eaten", "was eating"], correct:1},
{text:"She ________ for the bus for forty minutes when it finally arrived.", options:["waited", "was waiting", "had been waiting", "had waited"], correct:2},
{text:"No sooner ________ the stage than the audience applauded.", options:["she had entered", "had she entered", "she entered", "did she enter"], correct:1},
{text:"He used to ________ five kilometres every morning.", options:["run", "running", "ran", "have run"], correct:0},
{text:"While I ________ a shower, someone ________ my phone.", options:["took / stole", "was taking / stole", "took / was stealing", "was taking / was stealing"], correct:1},
{text:"I ________ already ________ breakfast, so I am not hungry.", options:["have / eaten", "had / eaten", "did / eat", "was / eating"], correct:0},
{text:"She ________ in this company since 2010.", options:["worked", "is working", "has worked", "had worked"], correct:2},
{text:"Have you ________ him lately?", options:["seen", "saw", "see", "been seeing"], correct:0},
{text:"It is the most beautiful painting I ________.", options:["ever saw", "have ever seen", "had ever seen", "ever see"], correct:1},
{text:"They ________ five matches so far this season.", options:["won", "win", "have won", "had won"], correct:2},
{text:"Einstein ________ the theory of relativity. [Choose the correct tense]", options:["has developed", "developed", "had developed", "was developing"], correct:1},
{text:"This is the third time you ________ that same mistake.", options:["make", "made", "have made", "had made"], correct:2},
{text:"'________ you ever ________ to Japan?' 'Yes, I ________ there in 2018.'", options:["Have / been / went", "Did / go / went", "Have / gone / have gone", "Did / go / have gone"], correct:0},
{text:"We ________ each other for twenty years and we are still best friends.", options:["knew", "have known", "know", "had known"], correct:1},
{text:"She ________ the letter yet. It is still on the desk.", options:["hasn't posted", "didn't post", "hasn't been posting", "hadn't posted"], correct:0},
{text:"The government ________ new policies that will affect millions.", options:["announced", "announces", "has announced", "had announced"], correct:2},
{text:"Your eyes are red. ________ you ________ ?", options:["Did / cry", "Have / cried", "Have / been crying", "Were / crying"], correct:2},
{text:"I ________ English for six years and I am still learning.", options:["study", "am studying", "have studied", "have been studying"], correct:3},
{text:"She ________ the same song all morning. I am getting tired of it.", options:["sings", "has sung", "is singing", "has been singing"], correct:3},
{text:"How long ________ you ________ for the bus?", options:["did / wait", "have / waited", "have / been waiting", "are / waiting"], correct:2},
{text:"He ________ French for two years, so he can now hold a conversation.", options:["is learning", "learned", "has been learning", "had been learning"], correct:2},
{text:"Look at those clouds! It ________ soon.", options:["will rain", "is going to rain", "is raining", "rains"], correct:1},
{text:"'The phone is ringing.' 'I ________ it.'", options:["am going to answer", "answer", "will answer", "am answering"], correct:2},
{text:"By this time next year, she ________ her degree.", options:["will complete", "is completing", "will have completed", "will be completing"], correct:2},
{text:"This time tomorrow, we ________ on the beach in Mombasa.", options:["will sit", "are going to sit", "will be sitting", "will have sat"], correct:2},
{text:"If you study hard, you ________ the exam.", options:["pass", "will pass", "would pass", "are passing"], correct:1},
{text:"I ________ you as soon as I arrive.", options:["will call", "call", "am going to call", "will have called"], correct:0},
{text:"The president ________ a speech at noon tomorrow.", options:["will give", "gives", "is giving", "is going to give"], correct:2},
{text:"By the time you read this letter, I ________ the country.", options:["will leave", "am leaving", "will be leaving", "will have left"], correct:3},
{text:"Don't call him between 8 and 9. He ________ dinner with his family.", options:["will have", "will be having", "is going to have", "will have had"], correct:1},
{text:"I ________ my homework before the teacher arrives.", options:["will finish", "am finishing", "will have finished", "will be finishing"], correct:2},
{text:"If I ________ you, I would not have said that.", options:["were", "am", "had been", "was"], correct:0},
{text:"If she ________ harder, she ________ the scholarship.", options:["studied / will win", "had studied / would have won", "studies / would win", "studied / would win"], correct:3},
{text:"If you had told me the truth, I ________ angry.", options:["wouldn't be", "won't be", "wouldn't have been", "hadn't been"], correct:2},
{text:"Unless he ________ immediately, he will lose his job.", options:["will apologise", "apologises", "apologised", "would apologise"], correct:1},
{text:"I wish I ________ a better memory.", options:["have", "had", "have had", "would have"], correct:1},
{text:"She wishes she ________ to the party last night.", options:["went", "had gone", "would go", "goes"], correct:1},
{text:"If only it ________ raining! I want to go outside.", options:["stops", "stopped", "had stopped", "will stop"], correct:1},
{text:"Provided that you ________ on time, you will be admitted.", options:["arrive", "will arrive", "arrived", "would arrive"], correct:0},
{text:"'I am studying for my exams,' she said. She said that she ________ for her exams.", options:["is studying", "was studying", "studied", "had studied"], correct:1},
{text:"'I have finished the report,' he told his boss. He told his boss that he ________ the report.", options:["has finished", "had finished", "finished", "was finishing"], correct:1},
{text:"'The results will be announced tomorrow,' the teacher said. The teacher said that the results ________ the following day.", options:["will be announced", "would be announced", "are announced", "were announced"], correct:1},
{text:"'We had already submitted our project,' they said. They said that they ________ their project.", options:["had already submitted", "have already submitted", "already submitted", "were submitting"], correct:0},
{text:"'Don't touch the equipment,' the scientist warned. The scientist warned us ________ the equipment.", options:["not touch", "not to touch", "to not touch", "that we not touch"], correct:1},
{text:"'It might rain,' she said. She said that it ________ rain.", options:["might", "may", "could", "would"], correct:0},
{text:"After she ________ university, she plans to travel abroad.", options:["will finish", "finishes", "finished", "would finish"], correct:1},
{text:"He will not leave until his mother ________.", options:["will arrive", "arrives", "arrived", "is arriving"], correct:1},
{text:"Once the project ________ approved, we can begin construction.", options:["will be", "is", "would be", "was"], correct:1},
{text:"We will celebrate when he ________ his PhD.", options:["will complete", "completes", "completed", "would complete"], correct:1},
{text:"The pyramids ________ by ancient Egyptians.", options:["were built", "have been built", "had been built", "are built"], correct:0},
{text:"The new bridge ________ by the President next Friday.", options:["will open", "is going to open", "will be opened", "is opened"], correct:2},
{text:"Several suspects ________ by the police since last month.", options:["arrested", "have been arrested", "were arrested", "had been arrested"], correct:1},
{text:"By 2030, millions of electric cars ________ worldwide.", options:["will sell", "will be sold", "will have been sold", "are going to be sold"], correct:2},
{text:"He ________ his keys. He cannot get into the house.", options:["lost", "had lost", "has lost", "was losing"], correct:2},
{text:"When did you last ________ to him?", options:["speak", "spoke", "spoken", "have spoken"], correct:0},
{text:"It ________ three days since it last rained.", options:["is", "has been", "was", "had been"], correct:1},
{text:"I am tired because I ________ all day.", options:["worked", "was working", "have worked", "have been working"], correct:3},
{text:"Scarcely ________ she ________ the exam when the time was called.", options:["had / begun", "has / begun", "did / begin", "was / beginning"], correct:0},
{text:"She ________ him for years before they finally met in person.", options:["knew", "had known", "was knowing", "has known"], correct:1},
{text:"By the time this letter reaches you, I ________ already ________ on a flight to London.", options:["will / have boarded", "am / boarding", "will / be", "will / have been boarding"], correct:0},
{text:"They ________ the new policy for three hours when an objection was raised.", options:["discussed", "were discussing", "had been discussing", "have been discussing"], correct:2},
{text:"This road ________ since the earthquake damaged it last year.", options:["is closed", "was closed", "has been closed", "had been closed"], correct:2},
{text:"'I am going to resign,' the minister announced. The minister announced that he ________ to resign.", options:["is going", "was going", "would go", "went"], correct:1},
{text:"He denied ________ the money from the safe.", options:["to steal", "steal", "stealing", "that he stole"], correct:2},
{text:"She regrets ________ so many hours on social media in her youth.", options:["to spend", "spend", "that she spent", "spending"], correct:3},
{text:"I remember ________ this road as a child. It was unpaved.", options:["to walk", "walked", "walking", "walk"], correct:2},
{text:"He tried ________ the fire but nothing worked.", options:["to put out", "putting out", "put out", "having put out"], correct:0},
{text:"'Can you swim?' she asked me. She asked me ________ swim.", options:["if I could", "whether I can", "if could I", "that I could"], correct:0},
{text:"He is said ________ the richest man in the region.", options:["to be", "that he is", "being", "to have been"], correct:0},
{text:"The children ________ TV when their father entered the room.", options:["watched", "have watched", "were watching", "had watched"], correct:2},
{text:"She ________ all the money she earned that summer and now she is broke.", options:["spends", "spent", "has spent", "had spent"], correct:2},
{text:"I am sure that he ________ the assignment by the end of the day.", options:["will finish", "finishes", "will have finished", "is finishing"], correct:2},
{text:"Assuming that the flight ________ on time, we will arrive before sunset.", options:["departs", "will depart", "departed", "would depart"], correct:0},
{text:"They ________ each other at the airport for the first time after years of online communication.", options:["have met", "met", "were meeting", "had met"], correct:1},
{text:"The data ________ before it could be properly analysed.", options:["was deleted", "had been deleted", "has been deleted", "deleted"], correct:1},
{text:"'You must submit your application today,' the official said. The official said that I ________ my application that day.", options:["must submit", "had to submit", "should submit", "would submit"], correct:1},
{text:"She ________ English at university by the time she gets her scholarship.", options:["will study", "will be studying", "will have been studying", "is studying"], correct:2},
{text:"Not until the last student ________ the hall did the examiner collect the papers.", options:["left", "had left", "leaves", "has left"], correct:1},
{text:"The more you ________, the better your results will be.", options:["practice", "will practice", "practiced", "would practice"], correct:0},
{text:"Suppose you ________ the lottery, what would you do?", options:["win", "won", "had won", "would win"], correct:1},
{text:"I would rather you ________ a different approach to this problem.", options:["take", "took", "had taken", "would take"], correct:1},
{text:"It is time the government ________ action on climate change.", options:["takes", "take", "took", "should take"], correct:2},
{text:"He acts as if he ________ everything about the subject.", options:["knows", "knew", "has known", "would know"], correct:1},
{text:"They looked as though they ________ all night.", options:["work", "worked", "had been working", "have worked"], correct:2},
{text:"I ________ him three times and he still hasn't replied.", options:["emailed", "have emailed", "was emailing", "had emailed"], correct:1},
{text:"By the time she was 25, she ________ three novels.", options:["wrote", "has written", "had written", "was writing"], correct:2},
{text:"Long before the vote was cast, the outcome ________.", options:["was decided", "had been decided", "has been decided", "would be decided"], correct:1},
{text:"She was the only student who ________ the question correctly.", options:["answers", "had answered", "answered", "was answering"], correct:2},
{text:"'The teacher is explaining a difficult concept,' one student wrote. One student wrote that the teacher ________ a difficult concept.", options:["is explaining", "explained", "was explaining", "had been explaining"], correct:2},
{text:"She will have been working at this clinic for ten years ________ next March.", options:["since", "by", "for", "until"], correct:1},
{text:"We were shocked to hear that the minister ________ from his position.", options:["resigned", "had resigned", "has resigned", "resigns"], correct:1},
{text:"I ________ waiting for this moment my entire life.", options:["have been", "am", "was", "had been"], correct:0},
{text:"She ________ in London, ________ in Paris, and ________ in New York — all before she turned 30.", options:["lived / studied / worked", "had lived / had studied / had worked", "has lived / has studied / has worked", "was living / was studying / was working"], correct:1},
{text:"The patient ________ the medication for three weeks when the doctor changed the prescription.", options:["was taking", "took", "had been taking", "has been taking"], correct:2},
{text:"I ________ to tell you something important for a long time, but I never had the courage.", options:["wanted", "have been wanting", "had been wanting", "was wanting"], correct:2},
{text:"After ________ all night, he was exhausted.", options:["studying", "to study", "he studied", "study"], correct:0},
{text:"The food ________ when they finally sat down to eat.", options:["got cold", "was cold", "had gone cold", "has gone cold"], correct:2},
{text:"They ________ the project for two years by the time it was cancelled.", options:["were developing", "have been developing", "had been developing", "developed"], correct:2},
{text:"He is the most dedicated student the school ________ in years.", options:["saw", "sees", "has seen", "had seen"], correct:2},
{text:"Which sentence is INCORRECT?", options:["She has gone to Addis Ababa.", "She has been to Addis Ababa.", "She went to Addis Ababa last year.", "She has went to Addis Ababa."], correct:3},
{text:"'Has gone to' vs 'has been to' — which statement is TRUE?", options:["Both are identical in meaning", "'Has gone to' means she is there now; 'has been to' means she visited and returned", "'Has been to' means she is there now; 'has gone to' means she visited and returned", "Both require the person to be dead"], correct:1},
{text:"He ________ here for six months. (He is still here.)", options:["was", "is", "has been", "had been"], correct:2},
{text:"'When I was a student, I would study until midnight.' The word 'would' here expresses:", options:["A future plan", "A past habitual action", "A conditional action", "A reported speech"], correct:1},
        ],
        "conditionals":[
            {text:"If you heat ice, it ________ water.", options:["becomes","will become","would become","became"], correct:0},
{text:"Metals ________ when you heat them.", options:["will expand","would expand","expand","expanded"], correct:2},
{text:"If you do not water plants regularly, they ________.", options:["die","will die","would die","died"], correct:0},
{text:"She always feels better if she ________ enough sleep.", options:["gets","will get","would get","got"], correct:0},
{text:"If you press this button, the machine ________.", options:["stops","will stop","would stop","had stopped"], correct:0},
{text:"He ________ late to every meeting if nobody reminds him.", options:["comes","will come","would come","came"], correct:0},
{text:"If the temperature drops below zero, water ________ ice.", options:["will become","becomes","became","would become"], correct:1},
{text:"She ________ her medication on time if she wants to recover.", options:["takes","must take","will take","took"], correct:1},
{text:"If it ________ tomorrow, the outdoor ceremony will be moved indoors.", options:["rains","will rain","rained","would rain"], correct:0},
{text:"Unless he ________ his application before Friday, he will not be considered.", options:["submits","will submit","submitted","had submitted"], correct:0},
{text:"I ________ you as soon as I hear the results.", options:["will call","call","am calling","would call"], correct:0},
{text:"She will not get the promotion ________ she improves her performance significantly.", options:["if","unless","although","until"], correct:1},
{text:"Provided that all members ________ in favour, the motion will be passed.", options:["vote","will vote","voted","would vote"], correct:0},
{text:"If he ________ the instructions carefully, he would have assembled it correctly.", options:["reads","read","had read","would read"], correct:2},
{text:"She would not be in this situation if she ________ the warning.", options:["heeded","had heeded","would heed","heeds"], correct:1},
{text:"If I ________ you, I would not have trusted him with that information.", options:["am","were","was","had been"], correct:1},
{text:"He would have passed the board exam if he ________ more seriously.", options:["studied","studies","had studied","would study"], correct:2},
{text:"If they ________ the contract, they would have avoided the lawsuit entirely.", options:["read","had read","would read","were reading"], correct:1},
{text:"She ________ the scholarship if she had applied on time.", options:["would receive","would have received","will receive","had received"], correct:1},
{text:"Had he informed us earlier, we ________ appropriate arrangements.", options:["made","could make","could have made","can make"], correct:2},
{text:"________ she known about the side effects, she would never have taken the medication.", options:["If","Had","Were","Should"], correct:1},
{text:"Were he to resign, the entire department ________ into chaos.", options:["falls","would fall","will fall","fell"], correct:1},
{text:"Should you ________ any irregularities, report them to the supervisor immediately.", options:["notice","noticed","have noticed","noticing"], correct:0},
{text:"But for the intervention of the rescue team, the miners ________.", options:["would die","had died","would have died","were dying"], correct:2},
{text:"He speaks as though he ________ the final authority on the matter.", options:["is","were","has been","would be"], correct:1},
{text:"She treats the staff as if she ________ the owner of the company.", options:["is","was","were","had been"], correct:2},
{text:"If only I ________ more time to prepare for the presentation!", options:["have","had","would have","have had"], correct:1},
{text:"I wish the government ________ more attention to rural healthcare.", options:["pays","paid","has paid","would pay"], correct:3},
{text:"He regrets that he ________ the opportunity when it was offered.", options:["did not take","had not taken","would not take","does not take"], correct:1},
{text:"If the director ________ the budget cuts, the project would still be running.", options:["approved","had not approved","would not approve","does not approve"], correct:1}
        ],

        "Active & Passive":[
            {text:"The report ________ by the committee before the deadline.", options:["submitted","was submitted","has submitted","submits"], correct:1},
{text:"A decision ________ by the board before the end of the month.", options:["will make","will be made","makes","is making"], correct:1},
{text:"The suspect ________ for questioning early this morning.", options:["arrested","was arrested","has arrested","is arrested"], correct:1},
{text:"The ancient ruins ________ by tourists from around the world every year.", options:["visit","are visiting","are visited","have visited"], correct:2},
{text:"The medicine ________ three times a day as directed by the doctor.", options:["should take","should be taken","takes","is taking"], correct:1},
{text:"It ________ that several officials were involved in the scandal.", options:["is alleged","alleges","alleged","was alleging"], correct:0},
{text:"He ________ to have left the country before the arrest warrant was issued.", options:["is believed","believes","believed","was believing"], correct:0},
{text:"The contract ________ by both parties before it can take legal effect.", options:["must sign","must be signed","signs","is being sign"], correct:1},
{text:"Several witnesses ________ by the defence attorney during the trial.", options:["questioned","were questioned","have questioned","are questioning"], correct:1},
{text:"The new policy ________ by the time parliament reconvenes next session.", options:["will draft","will be drafted","has drafted","drafts"], correct:1},
{text:"She was seen ________ the restricted area without authorisation.", options:["enter","to enter","entering","to have entered"], correct:2},
{text:"The injured were ________ to the nearest hospital by helicopter.", options:["flown","flying","fly","been flown"], correct:0},
{text:"The data ________ carefully before the final report can be published.", options:["must analyse","must be analysed","is analysing","has analysed"], correct:1},
{text:"A replacement will ________ for the damaged equipment within the week.", options:["arrange","be arranged","have arranged","arranging"], correct:1},
{text:"The bridge ________ by engineers for the past six months.", options:["has been inspecting","has been inspected","is inspecting","inspected"], correct:1},
{text:"He was made ________ in front of the entire assembly.", options:["apologise","to apologise","apologising","apologised"], correct:1},
{text:"The accused ________ guilty by the jury after three days of deliberation.", options:["found","was found","has found","finding"], correct:1}
        ],

        "Reported Speech":[
            {text:"The audience ________ to remain seated during the entire performance.", options:["requested","were requested","have requested","requesting"], correct:1},
{text:"'I am preparing for the entrance examination,' she told her parents.", options:["She told her parents that she is preparing for the entrance examination.","She told her parents that she was preparing for the entrance examination.","She told her parents that she had been preparing for the entrance examination.","She told her parents that she prepares for the entrance examination."], correct:1},
{text:"'We have already submitted our final report,' the team announced.", options:["The team announced that they already submitted their final report.","The team announced that they have already submitted their final report.","The team announced that they had already submitted their final report.","The team announced that they will submit their final report."], correct:2},
{text:"'The minister will address the nation tomorrow,' the spokesman said.", options:["The spokesman said that the minister will address the nation the next day.","The spokesman said that the minister would address the nation the following day.","The spokesman said that the minister addressed the nation the next day.","The spokesman said that the minister had addressed the nation the following day."], correct:1},
{text:"'Don't use your phones during the examination,' the invigilator warned the students.", options:["The invigilator warned the students not to use their phones during the examination.","The invigilator warned the students don't use their phones.","The invigilator warned the students to not using their phones during examination.","The invigilator warned the students that they didn't use their phones."], correct:0},
{text:"'Why didn't you attend the review session?' the teacher asked the student.", options:["The teacher asked the student why he didn't attend the review session.","The teacher asked the student why hadn't he attended the review session.","The teacher asked the student why he hadn't attended the review session.","The teacher asked the student why he has not attended the review session."], correct:2},
{text:"'The earth revolves around the sun,' the science teacher explained.", options:["The science teacher explained that the earth revolved around the sun.","The science teacher explained that the earth revolves around the sun.","The science teacher explained that the earth had revolved around the sun.","The science teacher explained that the earth will revolve around the sun."], correct:1},
{text:"'I had finished the assignment before the power went out,' he said.", options:["He said that he had finished the assignment before the power went out.","He said that he finished the assignment before the power went out.","He said that he has finished the assignment before the power went out.","He said that he would finish the assignment before the power went out."], correct:0},
{text:"'You must appear before the disciplinary committee by Thursday,' the dean told her.", options:["The dean told her that she must appear before the committee by Thursday.","The dean told her that she had to appear before the committee by Thursday.","The dean told her that she should appear before the committee by Thursday.","The dean told her to appearing before the committee by Thursday."], correct:1},
{text:"'Can you explain the difference between the two terms?' she asked the professor.", options:["She asked the professor if he could explain the difference between the two terms.","She asked the professor if he can explain the difference between the two terms.","She asked the professor could he explain the difference between the two terms.","She asked the professor that he explain the difference between the two terms."], correct:0},
{text:"'We were conducting research when the funding was suddenly withdrawn,' the scientists said.", options:["The scientists said that they conducted research when funding had been withdrawn.","The scientists said that they had been conducting research when the funding had suddenly been withdrawn.","The scientists said that they were conducting research when the funding was suddenly withdrawn.","The scientists said that they had been conducting research when the funding was suddenly withdrawn."], correct:3},
{text:"'I will have completed my dissertation by June,' she told her supervisor.", options:["She told her supervisor that she will have completed her dissertation by June.","She told her supervisor that she would have completed her dissertation by June.","She told her supervisor that she completed her dissertation by June.","She told her supervisor that she had completed her dissertation by June."], correct:1},
{text:"He claimed ________ the files before the server crashed.", options:["to back up","to have backed up","backing up","that he backs up"], correct:1},
{text:"She denied ________ the confidential documents to the press.", options:["to leak","to have leaked","leaking","that she leaked"], correct:2},
{text:"The chairperson admitted ________ aware of the financial irregularities.", options:["to be","to have been","being","that she is"], correct:2},
{text:"She was late ________ the traffic was unusually heavy that morning.", options:["despite","although","because","in spite of"], correct:2},
{text:"________ extensive preparations, the event did not go as planned.", options:["Although","Despite","Because of","Since"], correct:1}
        ],

        "Conjunctions & Prepositions":[
            {text:"He is fluent in three languages; ________, he still struggles with formal writing.", options:["therefore","furthermore","however","consequently"], correct:2},
{text:"She finished the marathon ________ injuring her knee in the final kilometre.", options:["although","despite","because of","even though"], correct:1},
{text:"The delegation arrived late ________ an unexpected delay at the border.", options:["although","because","due to","in spite of"], correct:2},
{text:"________ the criticism she received, she continued to defend her position publicly.", options:["Due to","Although","Despite","Since"], correct:2},
{text:"Not only ________ the test, but he also achieved the highest mark in the class.", options:["he passed","passed he","did he pass","he did pass"], correct:2},
{text:"The agreement was signed; ________, both parties have since disputed its terms.", options:["nevertheless","therefore","furthermore","accordingly"], correct:0},
{text:"She worked through the night ________ meet the submission deadline.", options:["so as to","despite","although","in spite of"], correct:0},
{text:"________ the lack of resources, the research team produced groundbreaking results.", options:["Because","Despite","Although","Since"], correct:1},
{text:"He succeeded ________ facing considerable opposition from senior management.", options:["although","despite","in spite","even"], correct:1},
{text:"She was promoted ________ being the most junior member of the department.", options:["despite","although","because","in spite"], correct:0},
{text:"He apologised ________ causing unnecessary delays in the project timeline.", options:["about","for","of","to"], correct:1},
{text:"She is responsible ________ overseeing all financial transactions in the department.", options:["of","about","to","for"], correct:3},
{text:"The committee consists ________ seven elected members and three appointed advisers.", options:["from","of","with","about"], correct:1},
{text:"He is not accustomed ________ being questioned about his professional decisions.", options:["to","of","for","about"], correct:0},
{text:"She insisted ________ reviewing every document personally before signing.", options:["about","for","on","to"], correct:2},
{text:"The board members disagreed ________ the proposed changes to the constitution.", options:["about","with","to","at"], correct:0},
{text:"He was acquitted ________ all charges after the evidence was re-examined.", options:["from","for","of","about"], correct:2},
{text:"She prevented her colleague ________ making a serious procedural error.", options:["to","of","against","from"], correct:3},
{text:"The project was delayed ________ three months due to unforeseen complications.", options:["for","during","since","from"], correct:0},
{text:"She has been working on this case ________ the beginning of the academic year.", options:["for","during","since","from"], correct:2},
{text:"He congratulated his colleague ________ being selected for the international fellowship.", options:["for","on","about","to"], correct:1},
{text:"The students were warned ________ the consequences of academic dishonesty.", options:["about","of","for","from"], correct:0},
{text:"She was deeply absorbed ________ her research when the announcement was made.", options:["with","on","in","at"], correct:2},
{text:"He is known ________ his sharp analytical skills and attention to detail.", options:["by","for","with","about"], correct:1},
{text:"She arrived ________ the conference hall just as the keynote speaker was being introduced.", options:["to","in","at","into"], correct:2},
{text:"The policy has been in effect ________ the last general election.", options:["for","since","during","from"], correct:1},
{text:"She is married ________ a diplomat and lives abroad for most of the year.", options:["with","for","to","by"], correct:2} 
        ],

        "Question Tags & Word Order":[
            {text:"He succeeded ________ securing a research grant after five failed applications.", options:["at","to","in","on"], correct:2},
{text:"The CEO resigned ________ pressure from shareholders following the financial scandal.", options:["because","under","despite","from"], correct:1},
{text:"He was charged ________ fraud and misuse of public funds.", options:["of","for","about","with"], correct:3},
{text:"The reforms will benefit all citizens, ________ they?", options:["won't","will","don't","wouldn't"], correct:0},
{text:"Nobody told you about the change in schedule, ________ they?", options:["didn't","did","weren't","hadn't"], correct:1},
{text:"She had barely recovered from the first setback when the second occurred, ________ she?", options:["had","hadn't","didn't","has"], correct:1},
{text:"Let's not rush into a decision we might regret, ________ we?", options:["will","shall","don't","won't"], correct:1},
{text:"He would rather the matter not be discussed in public, ________ he?", options:["would","wouldn't","will","won't"], correct:1},
{text:"You had better reconsider your position before the final vote, ________ you?", options:["hadn't","didn't","wouldn't","shouldn't"], correct:0},
{text:"Everyone in the department was notified about the restructuring, ________ they?", options:["wasn't he","weren't they","haven't they","didn't they"], correct:1},
{text:"Nothing significant was found during the initial investigation, ________ it?", options:["was","wasn't","did","didn't"], correct:0},
{text:"She used to hold a senior position in the ministry, ________ she?", options:["used","usedn't","didn't","hadn't"], correct:2},
{text:"I am not mistaken about the date of the submission, ________ I?", options:["amn't","am not","aren't","am"], correct:2},
{text:"They need not submit the secondary documents unless specifically requested, ________ they?", options:["do","don't","need","needn't"], correct:2},
{text:"It was the delegate from the northern region ________ raised the issue of resource allocation.", options:["who","which","whom","that he"], correct:0},
{text:"It was not until the third attempt ________ she finally solved the equation.", options:["when","which","that","where"], correct:2},
{text:"________ astonished were the examiners by her performance that they requested a special review.", options:["Very","Such","So","Too"], correct:2},
{text:"Only when the final results were published ________ the extent of the disparity.", options:["they understood","did they understand","they did understand","understood they"], correct:1},
{text:"Rarely ________ a candidate demonstrate such depth of knowledge under examination conditions.", options:["does","did","a candidate does","do"], correct:0},
{text:"At no point during the proceedings ________ the defendant's legal representative object.", options:["did","does","had","was"], correct:0},
{text:"Not until the investigation was concluded ________ the full findings made public.", options:["were","they were","was they","have been"], correct:0},
{text:"So complex ________ the legislation that even experienced lawyers disagreed on its interpretation.", options:["it was","the legislation was","was","that was"], correct:2},
{text:"Under no circumstances ________ personal electronic devices be used during the written examination.", options:["must","should","are","may"], correct:0},
{text:"Neither the principal findings nor the supplementary evidence ________ sufficient to justify a retrial.", options:["was","were","has been","is"], correct:0},
{text:"The faster the reforms ________ implemented, the sooner the population will benefit.", options:["were","are","being","will be"], correct:1},
{text:"What remains unclear to most observers ________ the long-term consequences of the decision.", options:["are","is","were","being"], correct:1},
{text:"Seldom ________ a government official speak so candidly about internal policy failures.", options:["does","did","you see","have"], correct:0},
{text:"Such ________ the impact of the drought that entire harvests were lost across the region.", options:["is","was","were","has been"], correct:1},
{text:"Only after extensive consultation ________ the committee reach a unanimous decision.", options:["did","does","had","the committee"], correct:0}
        ],

        "Adjectives & Adverbs":[
{text:"Which sentence uses an adjective in the PREDICATIVE position?",options:["The tired child slept early.","She wore a beautiful dress.","The soup tastes delicious.","He bought an expensive car."],correct:2},
{text:"Identify the correct order of adjectives: 'She carried a ___ bag.'",options:["leather small old brown","small old brown leather","old small leather brown","brown leather old small"],correct:1},
{text:"Which word functions as an adjective in: 'The sleeping baby looked peaceful'?",options:["sleeping","baby","looked","peaceful"],correct:0},
{text:"Choose the sentence where 'old' is used comparatively in a non-standard but accepted form.",options:["He is older than his brother.","He is the eldest of the three.","My elder sister lives abroad.","She is as old as I am."],correct:2},
{text:"Which underlined word is NOT functioning as an adjective? 'The (broken) window, (his) wallet, the car (runs) fast, and the (golden) rule.'",options:["broken","his","golden","All are adjectives"],correct:2},
{text:"Which sentence contains a compound adjective used correctly?",options:["She is a well-known author.","She is a well known author.","She is a wellknown author.","She is a well knowing author."],correct:0},
{text:"'The news made her sad.' The adjective here is:",options:["news","made","sad","her"],correct:2},
{text:"Which adjective form is INCORRECT? 'This is the most unique design I've seen.'",options:["It is correct because unique can be modified","Incorrect — unique is absolute and cannot take 'most'","Incorrect — it should be 'more unique'","Incorrect — it should be 'uniquer'"],correct:1},
{text:"In 'Many students passed the exam', 'Many' is what type of adjective?",options:["Demonstrative","Interrogative","Indefinite","Numeral"],correct:2},
{text:"Choose the sentence with the correct superlative form.",options:["She is the most cleverest student.","She is the cleverest student.","She is the more cleverest student.","She is cleverest student."],correct:1},
{text:"Which sentence uses a PARTICIPIAL ADJECTIVE correctly?",options:["The bored students left the hall.","The boring students left the hall.","Both A and B are correct depending on meaning.","Neither is a participial adjective."],correct:2},
{text:"'Whose bag is this?' The word 'Whose' functions as:",options:["A pronoun only","An interrogative adjective","A relative adverb","A demonstrative adjective"],correct:1},
{text:"Which sentence contains an ATTRIBUTIVE adjective?",options:["The milk smells sour.","He feels nervous.","She bought a red umbrella.","The answer seems correct."],correct:2},
{text:"Choose the sentence where the adjective is incorrectly positioned.",options:["It was a difficult enough task.","She wore a dress red.","He is tall enough to reach it.","I need something cold to drink."],correct:1},
{text:"'Enough' as an adjective comes _____ the noun it modifies.",options:["before","after","either before or after","never directly beside"],correct:0},
{text:"Which is a proper adjective?",options:["beautiful","Victorian","thoughtful","ancient"],correct:1},
{text:"'The ill patient was given medicine.' Here 'ill' is:",options:["An adverb","A predicative adjective","An attributive adjective","A noun adjunct"],correct:2},
{text:"Identify the sentence where 'little' is used as a negative-sense adjective (meaning 'hardly any').",options:["She is a little tired.","There is little hope left.","The little girl smiled.","He gave a little wave."],correct:1},
{text:"Which sentence uses 'elder' correctly?",options:["She is elder than me.","My elder brother is a doctor.","She is the elderest child.","He is much elder now."],correct:1},
{text:"'The news is worrying.' Which type of adjective is 'worrying'?",options:["Participial adjective from present participle","Participial adjective from past participle","A simple descriptive adjective","An adverb modifying 'news'"],correct:0},
{text:"In the sentence 'Give me something interesting to read', 'interesting' modifies:",options:["me","give","something","read"],correct:2},
{text:"Which adjective form is used to compare exactly TWO things?",options:["Positive","Comparative","Superlative","Absolute"],correct:1},
{text:"'The glass is half full.' Here 'half' is functioning as:",options:["An adverb","An adjective modifying 'glass'","An adjective modifying 'full'","A noun"],correct:2},
{text:"Which sentence is grammatically correct regarding adjective comparison?",options:["This is the most farthest point.","This is the farthest point.","This is the most far point.","This is the farther point of all."],correct:1},
{text:"'A three-year-old child' — why is this hyphenated?",options:["Because it follows a linking verb","Because it is a compound adjective used attributively","Because numerals always need hyphens","Because 'old' is a past participle"],correct:1},
{text:"Which sentence uses an adjective AFTER an object correctly (object complement)?",options:["She found the book interested.","She found the book interesting.","She found interesting the book.","She found the interesting book."],correct:1},
{text:"'Few students attended.' vs 'A few students attended.' The difference is:",options:["No difference in meaning","'Few' emphasizes scarcity (nearly none); 'A few' emphasizes some presence","'A few' is informal; 'few' is formal","'Few' is an adverb; 'A few' is an adjective"],correct:1},
{text:"Which word in 'The content students performed well' is an adjective?",options:["content","students","performed","well"],correct:0},
{text:"'The harder you work, the better the results.' 'Harder' and 'better' are used as:",options:["Adverbs in parallel structure","Comparative adjectives in a correlative structure","Superlative adjectives","Absolute adjectives"],correct:1},
{text:"Which sentence correctly uses 'latter' as an adjective?",options:["The latter half of the year is busier.","She left on the latter.","The latter is more expensive.","Latter is a good choice."],correct:0},
{text:"'Unkempt', 'disheveled', and 'distraught' are adjectives that are typically used in which position?",options:["Attributive only","Predicative only","Both attributive and predicative","Neither; they are adverbs"],correct:2},
{text:"Choose the sentence with an incorrect comparative adjective.",options:["She is more creative than her sister.","He is more taller than I expected.","This road is less crowded than that one.","The task seems more complex than before."],correct:1},
{text:"In 'The very thought of it scares me', 'very' is functioning as:",options:["An adverb modifying 'scares'","An adjective modifying 'thought'","An intensifier adjective","An adverb modifying 'thought'"],correct:1},
{text:"Which sentence contains a NOUN used as an adjective (noun adjunct)?",options:["The golden trophy shone brightly.","The stone wall was very old.","The wall looked old.","She painted the wall golden."],correct:1},
{text:"'The accused was released.' 'Accused' functions as:",options:["A verb","An adjective used as a noun (nominalized adjective)","A past participial adjective","An adverb"],correct:1},
{text:"Select the sentence where the adjective clause is correctly placed.",options:["The boy broke the window who is tall.","The boy who is tall broke the window.","The boy broke who is tall the window.","Who is tall the boy broke the window."],correct:1},
{text:"In 'She has an extraordinary talent', 'extraordinary' is a(n):",options:["Compound adjective","Adjective formed with prefix extra-","Absolute adjective","Proper adjective"],correct:1},
{text:"Which sentence uses 'afraid' correctly as an adjective?",options:["The afraid child hid.","She was afraid of the dark.","He gave an afraid look.","The afraid expression on his face."],correct:1},
{text:"Which type of adjective is used in 'Each student must submit a report'?",options:["Demonstrative","Distributive","Indefinite","Interrogative"],correct:1},
{text:"'The more, the merrier.' This structure uses comparatives to express:",options:["That more people create more noise","A proportional relationship between two things","A superlative idea in disguise","An absolute comparison"],correct:1},

// ── ADVERBS (40 Questions) ─────────────────────────────────

{text:"Which sentence uses an adverb of DEGREE correctly?",options:["She sings beautifully always.","He is extremely talented.","He runs fast yesterday.","She almost went there."],correct:1},
{text:"'He arrived late.' vs 'He arrived lately.' Which is correct if the meaning is 'not on time'?",options:["lately","late","Both are correct","Neither is correct"],correct:1},
{text:"Identify the adverb in: 'She quietly closed the door and left.'",options:["closed","door","quietly","left"],correct:2},
{text:"Which sentence places the adverb of frequency in the CORRECT position?",options:["She always has been honest.","She has always been honest.","She has been always honest.","Always she has been honest."],correct:1},
{text:"'Hardly' is a negative adverb. Which sentence uses it correctly?",options:["She hardly never goes out.","She can hardly breathe.","She doesn't hardly speak.","She hardly doesn't sleep."],correct:1},
{text:"'She works hard.' vs 'She hardly works.' The difference is:",options:["No meaningful difference","'Hard' means with great effort; 'hardly' means barely or almost not","'Hardly' is more formal than 'hard'","'Hard' is an adjective here, not an adverb"],correct:1},
{text:"Which adverb is an adverb of MANNER?",options:["soon","here","never","swiftly"],correct:3},
{text:"'Nearly' and 'near' are both adverbs. Which sentence uses 'near' as an adverb correctly?",options:["He nearly finished the work (barely finished).","Don't come near.","She near missed the bus.","He is near happy."],correct:1},
{text:"In 'She spoke very softly', which word is the adverb of degree?",options:["spoke","very","softly","she"],correct:1},
{text:"Which adverb is used correctly as a SENTENCE ADVERB?",options:["Fortunately, he survived the accident.","He, fortunately, survived the accident very.","Survived fortunately the accident.","The accident fortunately survived."],correct:0},
{text:"'She is a fast runner.' vs 'She runs fast.' In the second sentence 'fast' is:",options:["An adjective modifying 'she'","An adverb modifying 'runs'","An adjective modifying 'runner'","A noun"],correct:1},
{text:"Which of the following is NOT a conjunctive adverb?",options:["however","therefore","furthermore","although"],correct:3},
{text:"Choose the sentence that avoids a double negative correctly.",options:["I don't know nothing about it.","I know nothing about it.","I don't know anything about it.","Both B and C are correct."],correct:3},
{text:"'He explained the matter clearly enough.' Here 'enough' is modifying:",options:["the matter","explained","clearly","matter"],correct:2},
{text:"Identify the adverb in: 'The team played exceptionally well under pressure.'",options:["under","pressure","exceptionally","well"],correct:2},
{text:"Which sentence correctly uses 'good' and 'well'?",options:["She sings good.","She sings well.","She did good on the test.","She feels well about it."],correct:1},
{text:"'He could barely finish in time.' 'Barely' is an adverb of:",options:["Manner","Place","Degree","Time"],correct:2},
{text:"'Yet' can function as an adverb of time. Which sentence uses it correctly in this role?",options:["He has yet to arrive.","He arrived yet.","Yet he is tired.","He did not yet."],correct:0},
{text:"'She almost never complains.' The adverbs are:",options:["almost (degree), never (frequency)","almost (frequency), never (time)","almost (manner), never (negation)","almost (time), never (degree)"],correct:0},
{text:"In formal writing, which is correct when placing an adverb with an infinitive?",options:["To boldly go is acceptable in modern English.","To go boldly is the only formal option.","Boldly to go is the only formal option.","Split infinitives are always grammatically wrong."],correct:0},
{text:"'The exam was fairly difficult.' 'Fairly' belongs to which category of adverb?",options:["Adverb of manner","Adverb of degree","Adverb of frequency","Adverb of place"],correct:1},
{text:"Which sentence uses a relative adverb correctly?",options:["That is the house where I was born.","That is the house which where I was born.","That is the house in that I was born.","That is the house where was I born."],correct:0},
{text:"The comparative form of 'soon' is:",options:["sooner","more soon","soonest","more sooner"],correct:0},
{text:"'He no sooner arrived than she left.' 'No sooner' functions as:",options:["A conjunction pair only","A correlative adverb triggering subject-verb inversion","A double negative construction","A compound preposition"],correct:1},
{text:"'Seldom do we see such bravery.' Why is there subject-verb inversion here?",options:["It is a question form","A negative adverb at the start triggers inversion","It is a conditional sentence","It is an exclamatory sentence"],correct:1},
{text:"Which is the correct superlative adverb form of 'badly'?",options:["baddest","most badly","worst","most bad"],correct:2},
{text:"'She dresses smartly.' If we make it negative, the correct form is:",options:["She does not dress smartly.","She dresses not smartly.","She not dresses smartly.","She dresses unsmartly."],correct:0},
{text:"'He runs as quickly as she does.' This uses an adverb in which degree?",options:["Comparative","Superlative","Positive (equal comparison)","Absolute"],correct:2},
{text:"'Too' and 'very' are both intensifiers. Which sentence shows a meaningful distinction?",options:["He is very tired to study = He is too tired to study.","He is too tired to study implies he cannot study; 'very tired' does not.","'Too' and 'very' are interchangeable.","'Very' implies inability while 'too' just emphasizes."],correct:1},
{text:"'She speaks Italian fluently.' What type of adverb is 'fluently'?",options:["Degree","Frequency","Manner","Place"],correct:2},
{text:"Which sentence uses 'hard' as an adverb incorrectly?",options:["He tried hard to win.","She worked hard all day.","He thought hardly about the problem.","They studied hard before the exam."],correct:2},
{text:"In 'Surprisingly, the results were positive', which grammatical role does 'surprisingly' play?",options:["Adverb of manner modifying 'were'","Disjunct (sentence adverb) commenting on the whole sentence","Adverb of degree modifying 'positive'","Conjunctive adverb linking two sentences"],correct:1},
{text:"'Nowhere', 'everywhere', and 'somewhere' are adverbs of:",options:["Manner","Time","Degree","Place"],correct:3},
{text:"'I would rather stay.' 'Rather' here is an adverb functioning as:",options:["A degree modifier of 'stay'","A modal particle expressing preference","A manner adverb","A frequency adverb"],correct:1},
{text:"'She arrived immediately after the ceremony ended.' 'Immediately' modifies:",options:["arrived","after the ceremony ended","ended","she"],correct:1},
{text:"Which sentence uses the adverb 'well' as a predicate describing health?",options:["She did the job well.","She looks well today.","She performed well on stage.","She spoke well of him."],correct:1},
{text:"'Already' and 'yet' both relate to time, but which is used in negative sentences and questions?",options:["already","yet","both","neither"],correct:1},
{text:"'He runs faster than she does.' 'Faster' is the comparative form of which adverb?",options:["fast","fastly","quick","far"],correct:0},
{text:"Which adverb correctly completes this sentence with formal subject-verb inversion: 'Little ___ he know what awaited him.'?",options:["do","did","does","had"],correct:1},
{text:"'She was so exhausted that she fell asleep immediately.' 'So...that' is used here as:",options:["A correlative adverb structure showing result","A comparison structure","A conditional structure","A concessive structure"],correct:0},
        ] ,
        "Quantifiers , gerends & infinitives...":[
            {text:"________ of the information provided in the report was found to be inaccurate.", options:["A great deal","A large number","Many","Several"], correct:0},
{text:"She has ________ patience for bureaucratic delays than her predecessor.", options:["less","fewer","little","least"], correct:0},
{text:"________ student in the examination hall must submit their answer sheet before leaving.", options:["All","Every","Each of","Both"], correct:1},
{text:"He made ________ errors in his final paper that the examiner had to disqualify it.", options:["so much","such many","so many","such a lot"], correct:2},
{text:"________ of the delegates were present when the resolution was passed.", options:["A little","A few","Few","Little"], correct:2},
{text:"There is ________ evidence to support the defendant's claim of innocence.", options:["few","little","a few","fewer"], correct:1},
{text:"She spent ________ of her savings on professional development courses.", options:["most","the most","mostly","almost"], correct:0},
{text:"________ the participants completed the survey within the allocated time.", options:["Almost of","Almost all","Most of all","Nearly all of"], correct:1},
{text:"He has ________ knowledge of the subject to be appointed as a consultant.", options:["enough","sufficient of","too much","plenty"], correct:0},
{text:"________ the candidates were shortlisted despite submitting complete applications.", options:["Neither of","None of","Neither","No one"], correct:1},
{text:"She answered ________ of the questions correctly on her first attempt.", options:["none","not any","neither","no"], correct:0},
{text:"There were ________ applicants this year than last, yet the competition was fiercer.", options:["less","more fewer","fewer","less amount of"], correct:2},
{text:"He ate ________ food at the reception that he felt ill on the way home.", options:["so many","such","so much","such a"], correct:2},
{text:"________ member of the research team contributed equally to the final publication.", options:["Every","All","Both","Each"], correct:3},
{text:"The committee rejected ________ proposals submitted during the second round.", options:["all of","all the","all","both of the"], correct:1},
{text:"She ________ to accept the offer before considering the long-term implications.", options:["avoided to accept","avoided accepting","avoided accept","was avoiding to accept"], correct:1},
{text:"He admitted ________ the evidence before the investigating team arrived.", options:["to destroy","destroy","to have destroyed","having destroyed"], correct:3},
{text:"She resented ________ for a mistake that was not entirely her responsibility.", options:["to blame","being blamed","to be blamed","blame"], correct:1},
{text:"The director refused ________ on the ongoing negotiations with the union.", options:["commenting","to comment","comment","to be commenting"], correct:1},
{text:"He is looking forward to ________ his colleagues at the annual conference.", options:["see","seeing","have seen","be seeing"], correct:1},
{text:"She could not help ________ when she heard the absurd explanation.", options:["to laugh","laugh","laughing","to be laughing"], correct:2},
{text:"The board postponed ________ on the proposed merger until the audit was complete.", options:["to vote","vote","voting","to have voted"], correct:2},
{text:"He spent the entire evening ________ through the dense legal documentation.", options:["to go","going","go","to be going"], correct:1},
{text:"She was the first candidate ________ all the requirements for the position.", options:["meeting","to meet","having met","who meeting"], correct:1},
{text:"The administration is yet ________ a satisfactory response to the grievances raised.", options:["to provide","providing","to have provided","provided"], correct:0},
{text:"She managed ________ the deadline despite facing significant technical challenges.", options:["meeting","to meet","to have met","meet"], correct:1},
{text:"He kept ________ the same justification regardless of the evidence presented against him.", options:["to repeat","to have repeated","repeating","repeat"], correct:2},
{text:"She proposed ________ the meeting to a larger venue to accommodate all stakeholders.", options:["to move","moving","move","to have moved"], correct:1},
{text:"They were reported ________ the premises without authorisation the previous night.", options:["to enter","entering","to have entered","entered"], correct:2},
{text:"The governor is expected ________ a statement on the matter before the end of the week.", options:["issuing","to issue","issue","to have been issuing"], correct:1},
{text:"He pretended ________ the conversation that took place in his absence.", options:["not to overhear","not overhearing","to not overhear","not having overheard"], correct:0},
{text:"She is accustomed to ________ under considerable pressure without compromising quality.", options:["work","working","have worked","be working"], correct:1},
{text:"The authority went on ________ the same ineffective policies despite widespread opposition.", options:["implementing","to implement","implement","to have implemented"], correct:0},
{text:"He stopped ________ after his doctor advised him about the health consequences.", options:["to smoke","smoke","smoking","to have smoked"], correct:2},
{text:"She stopped ________ the instructions before starting, which caused errors later.", options:["reading","to read","read","having read"], correct:1},
{text:"He remembered ________ the application form, but the office had no record of it.", options:["submitting","to submit","submit","to have been submitting"], correct:0},
{text:"She remembered ________ the registration form before the portal closed.", options:["submitting","to submit","submit","having submitted"], correct:1},
{text:"They tried ________ a new approach, but it proved equally ineffective.", options:["adopting","to adopt","adopt","to have adopted"], correct:0},
{text:"The technician tried ________ the system but could not identify the fault.", options:["restarting","to restart","restart","to have restarted"], correct:1},
{text:"He regrets ________ the position when it was first offered three years ago.", options:["to decline","declining","to have declined","not to decline"], correct:1},
{text:"She regrets ________ you that your application has been unsuccessful at this stage.", options:["to inform","informing","inform","to have informed"], correct:0},
{text:"I would rather ________ the decision after consulting the legal team.", options:["to make","making","make","have made"], correct:2},
{text:"She would prefer ________ the results before making any public announcement.", options:["to wait for","waiting for","wait for","to be waiting for"], correct:0},
{text:"He would sooner ________ than accept a compromise that undermines his principles.", options:["resign","to resign","resigning","have resigned"], correct:0},
{text:"I would rather you ________ the matter to the press without prior authorisation.", options:["not disclose","not to disclose","do not disclose","not disclosed"], correct:0},
{text:"She had rather ________ informed about the change in policy before it was implemented.", options:["been","be","to be","being"], correct:0},
{text:"He prefers ________ in writing rather than making verbal commitments.", options:["to communicate","communicating","communicate","to have communicated"], correct:0},
{text:"She prefers ________ the report reviewed by a colleague before submission.", options:["having","to have","have","to having"], correct:1},
{text:"He would prefer that the committee ________ its decision until further evidence is gathered.", options:["defers","defer","deferred","will defer"], correct:1},
{text:"She is used to ________ long hours during critical phases of the project.", options:["work","working","have worked","be working"], correct:1},
{text:"It took him several months to get used to ________ in such an unstructured environment.", options:["work","working","have worked","be working"], correct:1},
{text:"________ from a privileged background, she was deeply aware of systemic inequality.", options:["Despite coming","Although came","Despite came","In spite to come"], correct:0},
{text:"It is no use ________ about the decision now; it has already been finalised.", options:["to complain","complain","complained","complaining"], correct:3},
{text:"There is little point ________ an appeal if the evidence remains unchanged.", options:["to file","file","in filing","filed"], correct:2},
{text:"It is worth ________ the full implications of the contract before signing.", options:["to consider","consider","considered","considering"], correct:3},
{text:"He found it difficult ________ between his professional duties and personal commitments.", options:["balancing","balance","to balance","to be balancing"], correct:2},
{text:"She found the lecture too abstract ________ without a solid theoretical background.", options:["to follow","following","follow","for following"], correct:0},
{text:"The document was too complex ________ without specialised legal knowledge.", options:["to interpret","for interpreting","interpret","being interpreted"], correct:0},
{text:"The instructions were clear enough ________ without any additional guidance.", options:["following","to follow","follow","for follow"], correct:1},
{text:"He was fortunate enough ________ a mentor who guided him through the early stages.", options:["finding","find","to find","to have found"], correct:3},
{text:"She was too exhausted ________ coherently after the fourteen-hour shift.", options:["thinking","think","to think","for thinking"], correct:2},
{text:"He was the only official ________ publicly about the flaws in the implementation process.", options:["to speak","speaking","who spoke","who speaking"], correct:0},
{text:"________ a second language fluently opens doors that remain closed to others.", options:["Speak","Speaking","To speak","Having spoken"], correct:1},
{text:"________ the terms of the agreement carefully is essential before signing any contract.", options:["Understanding","Understand","To understand","Having understood"], correct:0},
{text:"________ under such conditions for extended periods can have lasting psychological effects.", options:["Work","To work","Working","Having worked"], correct:2},
{text:"She acknowledged ________ a conflict of interest in the matter before proceedings began.", options:["to have","having","to having","to have had"], correct:1},
{text:"The suspect is understood ________ the country several weeks before the investigation began.", options:["to leave","to have left","leaving","having left"], correct:1},
{text:"________ the meeting early was seen by many as an act of disrespect.", options:["Leaving","To leave","Leave","Having leave"], correct:0},
{text:"His tendency ________ under pressure was noted as a significant weakness.", options:["to underperform","of underperforming","underperforming","for underperform"], correct:0},
{text:"Her ability ________ complex information into accessible language set her apart.", options:["of translating","to translate","translating","for translate"], correct:1},
{text:"The decision ________ the contract was based on performance reviews.", options:["to terminate","of terminating","terminating","for terminate"], correct:0},
{text:"There are ________ exceptions to this rule in formal academic writing.", options:["a few","few of","a little","little of"], correct:0},
{text:"________ of the budget allocated for infrastructure has been spent on administrative costs.", options:["Most","The most","Mostly","A most"], correct:0},
{text:"He has ________ opportunities to prove himself, yet he has failed on each occasion.", options:["had many","had much","much","many of"], correct:0},
{text:"She demonstrated ________ skill and ________ patience throughout the negotiation.", options:["remarkable / remarkable","considerable / considerable","a remarkable / remarkable","remarkable / a remarkable"], correct:1},
{text:"The manager gave ________ attention to the junior staff's concerns during the review.", options:["little","a little","few","a few"], correct:0},
{text:"________ of what was said at the meeting has been accurately documented in the minutes.", options:["Many","Much","Several","A number"], correct:1},
{text:"He has ________ interest in pursuing a career in public service.", options:["not many","not much","little","few"], correct:2},
{text:"She gave ________ thought to the consequences before making her announcement.", options:["little","a little","few","fewer"], correct:0},
{text:"________ the applicants met the minimum requirements for the advertised position.", options:["Few of","A few of","Little","Much of"], correct:0},
{text:"He has spent ________ time abroad that he sometimes struggles to relate to local concerns.", options:["so many","such much","so much","such many"], correct:2},
{text:"She has ________ experience in this field to be considered for a junior position.", options:["enough of","sufficient","enough","plenty"], correct:2},
{text:"Neither of the proposed solutions ________ adequately addressed the root cause of the problem.", options:["have","has","were","are"], correct:1},
{text:"Each of the findings ________ reviewed independently before the report was finalised.", options:["were","have been","was","are"], correct:2},
{text:"The majority of the evidence ________ against the initial hypothesis.", options:["point","pointed","are pointing","were pointed"], correct:1},
{text:"A number of inconsistencies ________ discovered in the financial records.", options:["was","has been","were","is"], correct:2},
{text:"The number of unresolved complaints ________ increased significantly over the past year.", options:["have","had","has","were"], correct:2},
{text:"She enjoys ________ to classical music while working on complex analytical tasks.", options:["listen","to listen","listening","to have listened"], correct:2},
{text:"He tends ________ under pressure, which has affected his performance in high-stakes situations.", options:["to withdraw","withdrawing","withdraw","to be withdrawing"], correct:0},
{text:"The lawyer advised her client ________ anything to the investigators without legal counsel present.", options:["not to say","to not say","not saying","not say"], correct:0},
{text:"She could not bear ________ the truth concealed from the people who had been most affected.", options:["seeing","to see","to have seen","see"], correct:0},
{text:"He had difficulty ________ the financial projections within the timeframe given.", options:["to complete","completing","complete","to have completed"], correct:1},
{text:"The policy needs ________ before it can be effectively implemented across all departments.", options:["revising","to revise","to have revised","revised"], correct:0},
{text:"She was not ready to risk ________ everything she had built over the course of her career.", options:["to lose","lose","losing","to have lost"], correct:2},
{text:"The committee is considering ________ the evaluation criteria to ensure greater transparency.", options:["to revise","revise","revising","to have revised"], correct:2},
{text:"He cannot imagine ________ the same position for more than five years without a new challenge.", options:["to hold","holding","hold","to have held"], correct:1},
{text:"She was heard ________ about the management's decision during the lunch break.", options:["to complain","complaining","complain","to have complained"], correct:1},
{text:"He was made ________ his role in the cover-up during the closed hearing.", options:["to acknowledge","acknowledge","acknowledging","to have acknowledged"], correct:0},
{text:"The professor let the students ________ the examination one more time under supervised conditions.", options:["to attempt","attempting","attempt","to have attempted"], correct:2},
{text:"She was observed ________ the premises after official hours on several occasions.", options:["enter","to enter","entering","to have entered"], correct:2},
{text:"The new measures are intended ________ the growing gap between urban and rural service delivery.", options:["to address","addressing","address","to have addressed"], correct:0},
{text:"I would rather ________ the report carefully than submit it prematurely.", options:["review","to review","reviewing","to have reviewed"], correct:0},
{text:"She had rather ________ the position than work under those conditions any longer.", options:["leave","to leave","leaving","to have left"], correct:0},
{text:"He would sooner ________ the project independently than share credit with someone who contributed little.", options:["complete","to complete","completing","to have completed"], correct:0},
{text:"She prefers ________ the project in stages rather than attempting to complete it all at once.", options:["approaching","to approach","approach","to have approached"], correct:1},
{text:"She would prefer ________ the issue resolved before the board meeting rather than during it.", options:["having","to have","have","for having"], correct:0},
{text:"He is not the sort of person to ________ a commitment without fully intending to honour it.", options:["making","make","have made","be making"], correct:1},
{text:"________ her qualifications, she was not shortlisted for the senior position.", options:["Despite having","Although having","In spite to have","Even having"], correct:0},
{text:"There is no point ________ the same arguments that have already been rejected twice.", options:["to repeat","repeat","repeating","for repeating"], correct:2},
{text:"It is not worth ________ over a matter that will have no bearing on the final outcome.", options:["argue","arguing","to argue","to have argued"], correct:1},
{text:"The task proved far too demanding ________ within the original timeframe.", options:["completing","to complete","complete","for completing"], correct:1},
{text:"________ the implications of the policy change without consulting affected communities was widely criticised.", options:["Implementing","To implement","Implement","Having implement"], correct:0},
{text:"Her insistence on ________ every procedural step slowed the process considerably.", options:["follow","following","to follow","to have followed"], correct:1},
{text:"He had no intention of ________ to the demands made by the opposition.", options:["concede","to concede","conceding","to have conceded"], correct:2},
{text:"The board saw no alternative to ________ the project given the circumstances.", options:["suspend","to suspend","suspending","having suspend"], correct:2},
{text:"She is alleged ________ the confidential documents to a third party.", options:["leaking","to leak","to have leaked","to be leaking"], correct:2},
{text:"The findings are said ________ a significant shift in the government's approach to fiscal policy.", options:["to suggest","suggesting","to have suggested","to be suggesting"], correct:0},
{text:"The organisation appeared ________ the severity of the situation until it was too late.", options:["to underestimate","underestimating","to have underestimated","underestimated"], correct:2},
{text:"He seemed ________ of the consequences, yet he proceeded without any apparent concern.", options:["to be aware","aware","being aware","to have been aware"], correct:3},
{text:"She is known ________ exceptionally well under pressure, which is why she was selected.", options:["to perform","performing","to have performed","for performing"], correct:0},
        ],
        "Mixed":[
            {text:"She ________ have submitted the report yesterday; the deadline was today.", options:["must","should","needn't","can't"], correct:1},
{text:"The lights are off and the door is locked. He ________ still be in the building.", options:["must","can't","might","should"], correct:1},
{text:"You ________ bring your identification; they already have your records on file.", options:["must","should","needn't","mustn't"], correct:2},
{text:"________ you please forward the corrected version to all relevant departments?", options:["Will","Shall","Would","Should"], correct:2},
{text:"She ________ speak four languages fluently by the age of eighteen.", options:["could","was able to","can","might"], correct:1},
{text:"He ________ have taken the documents; he was not even in the office that day.", options:["must","should","can't","needn't"], correct:2},
{text:"The regulation states that all visitors ________ sign in at the reception upon arrival.", options:["must","should","shall","ought"], correct:0},
{text:"You ________ use your mobile phone in the examination hall under any circumstances.", options:["mustn't","needn't","shouldn't","can't"], correct:0},
{text:"She ________ have been informed before the decision was publicly announced.", options:["must","ought to","can","will"], correct:1},
{text:"By the time the results are released, she ________ have been waiting for over three months.", options:["will","would","shall","should"], correct:0},
{text:"He ________ be the new director; he only joined the organisation six months ago.", options:["mustn't","can't","needn't","shouldn't"], correct:1},
{text:"________ I take your coat, or would you prefer to keep it with you?", options:["Will","Shall","Must","Should"], correct:1},
{text:"She ________ have scored higher if she had managed her time more effectively.", options:["could","can","shall","must"], correct:0},
{text:"The committee members ________ disclose any personal interests that may affect their judgement.", options:["must","shall","should","ought to"], correct:3},
{text:"He ________ have arrived by now; his flight landed two hours ago.", options:["should","shall","can","will"], correct:0},
{text:"________ of her colleagues knew about the investigation until it was officially announced.", options:["None","Neither","No one of","Not any"], correct:0},
{text:"She referred to ________ incident that had occurred during the previous administration.", options:["a","an","the","—"], correct:0},
{text:"________ information you provided has been forwarded to the relevant department.", options:["A","An","The","—"], correct:2},
{text:"He is widely regarded as ________ most influential economist of his generation.", options:["a","an","the","—"], correct:2},
{text:"She has ________ extensive knowledge of international trade law.", options:["a","an","the","—"], correct:0},
{text:"________ justice must be served without fear or favour in a democratic society.", options:["A","An","The","—"], correct:3},
{text:"The delegation met ________ President at the state house for a briefing.", options:["a","an","the","—"], correct:2},
{text:"She holds ________ PhD in molecular biology from a leading research institution.", options:["a","an","the","—"], correct:1},
{text:"He plays ________ piano at a professional level and performs internationally.", options:["a","an","the","—"], correct:2},
{text:"________ accused has the right to legal representation during all stages of the proceedings.", options:["A","An","The","—"], correct:2},
{text:"She travels to ________ Netherlands twice a year for academic conferences.", options:["a","an","the","—"], correct:2},
{text:"________ honesty is the foundation upon which all professional relationships must be built.", options:["A","An","The","—"], correct:3},
{text:"The scientist who ________ the vaccine received an international award.", options:["he developed","developed","whom developed","that he developed"], correct:1},
{text:"The policy, ________ was introduced without adequate consultation, was met with widespread resistance.", options:["that","which","what","who"], correct:1},
{text:"The delegate ________ proposal was accepted by the majority later chaired the implementation committee.", options:["who","whose","which","whom"], correct:1},
{text:"The village ________ she grew up has changed beyond recognition over the past two decades.", options:["which","where","that","in that"], correct:1},
{text:"He is not the kind of person ________ makes commitments without intending to fulfil them.", options:["who","which","that","whom"], correct:0},
{text:"The reason ________ the project failed was a fundamental misalignment of objectives.", options:["why","which","that","for which"], correct:0},
{text:"She was appointed to the role by the minister, ________ she had previously worked for in an advisory capacity.", options:["who","whom","whose","which"], correct:1},
{text:"The year ________ the organisation was founded marked a turning point in regional development.", options:["when","which","that","in which"], correct:0},
{text:"There is very little ________ can be done at this stage to reverse the decision.", options:["what","that","which","who"], correct:1},
{text:"He applied for a position at the institute ________ research he had long admired.", options:["which","whose","that","of which"], correct:1},
{text:"The report, the conclusions of ________ have been widely disputed, was submitted to parliament last week.", options:["that","what","which","it"], correct:2},
{text:"She works ________ than any other member of the department, yet she receives the least recognition.", options:["harder","more hard","hardest","most hard"], correct:0},
{text:"The situation is ________ more complicated than it appeared at the initial assessment stage.", options:["far","very","much more","a lot more"], correct:0},
{text:"He speaks English ________ than he writes it, which is unusual for someone with his academic background.", options:["more fluently","most fluently","fluently more","more fluent"], correct:0},
{text:"The earlier report was ________ less comprehensive than the revised version submitted last month.", options:["far","much","considerably","significantly"], correct:0},
{text:"She is ________ the most capable candidate the selection panel has interviewed for this role.", options:["by far","by much","by all","by great"], correct:0},
{text:"The new procedure is ________ straightforward as the previous one, despite the claims made during the briefing.", options:["not so","not as","less","not more"], correct:1},
{text:"He responded ________ to the criticism than had been anticipated, which surprised the review panel.", options:["more calm","calmer","more calmly","most calmly"], correct:2},
{text:"________ the reforms are implemented, the more resistance the government will encounter.", options:["More rapidly","The more rapidly","Most rapidly","As more rapidly"], correct:1},
{text:"She performed ________ in the final assessment than she had in any of the practice sessions.", options:["more good","better","best","more better"], correct:1},
{text:"The situation is ________ serious than the official statement would suggest.", options:["more far","far more","much more far","very more"], correct:1},
{text:"He ________ arrived at the venue when the first session was announced.", options:["hard","hardly","scarcely had","barely had"], correct:1},
{text:"She works ________ and expects the same level of commitment from everyone around her.", options:["hard","hardly","hardily","harder"], correct:0},
{text:"The new appointment came as ________ surprise to most members of the organisation.", options:["quite a","quite","rather","a quite"], correct:0},
{text:"She found the assignment ________ challenging that she requested an extension from the supervisor.", options:["so","such","too","very"], correct:0},
{text:"It was ________ complex a matter to be resolved in a single afternoon session.", options:["so","such","too","very"], correct:0},
{text:"He is ________ experienced to make such an elementary error in a formal submission.", options:["too","enough","very","far"], correct:0},
{text:"The proposal was ________ well-received that the committee approved it without amendment.", options:["such","so","too","very"], correct:1},
{text:"She arrived ________ late to participate in the opening session of the conference.", options:["too","so","very","much"], correct:0},
{text:"The report was ________ well-written that it was submitted to the national journal without revision.", options:["too","very","so","such a"], correct:2},
{text:"He behaved in ________ reckless a manner that the panel had no choice but to recommend his suspension.", options:["such","so","a","too"], correct:1},
{text:"Neither the chairperson nor the vice-chairperson ________ present when the resolution was passed.", options:["were","was","have been","are"], correct:1},
{text:"The team, as well as the project coordinator, ________ been notified of the change in schedule.", options:["have","has","had","were"], correct:1},
{text:"A series of workshops ________ planned to address the capacity gaps identified in the assessment.", options:["have been","has been","were","are"], correct:1},
{text:"Not only the director but also her deputies ________ held accountable for the mismanagement of funds.", options:["was","were","has been","is"], correct:1},
{text:"The jury ________ still deliberating when the court adjourned for the evening.", options:["were","was","has been","have been"], correct:1},
{text:"Every document and every record ________ been scrutinised by the investigating authority.", options:["have","has","were","are"], correct:1},
{text:"Politics ________ a field that demands both intellectual rigour and practical judgment.", options:["are","were","is","have been"], correct:2},
{text:"The data ________ not support the conclusion drawn in the preliminary findings.", options:["do","does","is","are"], correct:0},
{text:"Either the officials or the minister ________ to appear before the committee by Friday.", options:["are","have","is","were"], correct:2},
{text:"He ________ himself to deliver the speech without notes, which impressed the entire audience.", options:["made","had","got","found"], correct:0},
{text:"She ________ herself unable to remain impartial given her personal connection to the case.", options:["made","found","got","had"], correct:1},
{text:"He cut ________ while preparing the documentation and had to leave work early.", options:["him","his","himself","oneself"], correct:2},
{text:"The delegates introduced ________ before the session formally commenced.", options:["them","their","themselves","theirs"], correct:2},
{text:"She blamed ________ for the breakdown in communication that led to the crisis.", options:["her","herself","hers","she"], correct:1},
{text:"The investigation ________ revealed what many had long suspected about the organisation's internal practices.", options:["itself","themselves","ourselves","himself"], correct:0},
{text:"________ being a highly experienced professional, he sought advice from a more senior colleague.", options:["Despite","In spite of","Even","Although"], correct:0},
{text:"Having ________ the evidence, the panel was in a better position to reach an informed conclusion.", options:["reviewed","reviewing","to review","been reviewed"], correct:0},
{text:"________ at a young age, she developed an unusually sophisticated understanding of institutional dynamics.", options:["Educating abroad","Educated abroad","Having educating abroad","Being educate abroad"], correct:1},
{text:"The proposal, ________ in response to widespread public concern, was fast-tracked through the legislative process.", options:["drafted","drafting","having drafting","to draft"], correct:0},
{text:"________ considered all available options, the committee reached a decision that satisfied the majority.", options:["Having","Being","After having","Both A and C"], correct:3},
{text:"She made her position ________ during the press conference, leaving no room for further speculation.", options:["clear","clearly","cleared","to clear"], correct:0},
{text:"The manager had the financial records ________ by an external firm before submitting them to the auditors.", options:["verify","verified","verifying","to verify"], correct:1},
{text:"She got the approval letter ________ within forty-eight hours, which exceeded all expectations.", options:["process","processed","processing","to process"], correct:1},
{text:"He had his application ________ after it was discovered that key documents had been omitted.", options:["rejecting","to reject","rejected","reject"], correct:2},
{text:"She kept the board ________ of all developments throughout the duration of the project.", options:["inform","informing","informed","to inform"], correct:2},
{text:"I had rather you ________ this matter to the full council than handle it within the subcommittee alone.", options:["refer","referred","to refer","referring"], correct:1},
{text:"He would sooner face criticism ________ compromise the integrity of the institution.", options:["than to","than","to than","instead"], correct:1},
{text:"She is the sort of person who ________ ask for help even when she clearly needs it.", options:["wouldn't","doesn't","won't","can't"], correct:0},
{text:"The more the government ________ the issue, the more public confidence continues to erode.", options:["ignores","will ignore","is ignoring","has ignored"], correct:0},
{text:"She had no sooner accepted the position ________ she was asked to lead the most challenging project in the organisation's history.", options:["when","than","that","then"], correct:1},
{text:"The situation was such ________ even the most experienced members of the team found it difficult to navigate.", options:["as","that","which","what"], correct:1},
{text:"It is high time the administration ________ the structural issues that have been undermining performance.", options:["addresses","addressed","will address","has addressed"], correct:1},
{text:"She spoke as though she ________ personally present when the decision was made.", options:["was","has been","had been","is"], correct:2},
{text:"He insisted that the full report ________ made available to all stakeholders before the meeting.", options:["is","was","be","will be"], correct:2},
{text:"It is essential that every team leader ________ a comprehensive progress update by the end of the week.", options:["submits","submitted","submit","will submit"], correct:2},
{text:"The committee recommended that the policy ________ reviewed before being extended to additional departments.", options:["is","was","be","should be"], correct:2},
{text:"She demanded that the decision ________ reversed immediately and without conditions.", options:["is","be","was","will be"], correct:1},
{text:"________ the investigation be extended, additional resources will need to be allocated.", options:["Should","Were","Had","If"], correct:0},
{text:"He was promoted not because of his connections but ________ his outstanding professional record.", options:["because","due to","owing to","on account"], correct:2},
{text:"She not only delivered the report on time ________ exceeded all the performance benchmarks set for the period.", options:["but also","but","and also","as well"], correct:0},
{text:"The decision was made not to proceed with the original plan ________ to explore a more sustainable alternative.", options:["but","but rather","instead","however"], correct:1},
{text:"She is both intellectually rigorous ________ deeply committed to the practical application of her research.", options:["and","as well","but also","or"], correct:0},
{text:"He raised the issue not to cause disruption ________ to draw attention to a genuine procedural oversight.", options:["and","or","but","so"], correct:2},
{text:"The policy was withdrawn ________ its unintended consequences became apparent to the administration.", options:["since","once","so that","in order that"], correct:1},
{text:"She waited until all the supporting documentation ________ before presenting the case to the tribunal.", options:["was compiled","compiled","had been compiled","has been compiled"], correct:2},
{text:"The findings were more significant ________ the research team had initially anticipated.", options:["as","than","that","like"], correct:1},
{text:"He phrased his objection in such a way ________ it could not be easily dismissed by the panel.", options:["that","which","as","so"], correct:0},
{text:"She left the meeting early, ________ prompted several members to question her commitment to the process.", options:["which","that","what","who"], correct:0},
{text:"The organisation's failure to act swiftly, ________ was foreseeable given its track record, cost it considerable public trust.", options:["that","which","what","this"], correct:1},
{text:"The statement he issued to the press differed significantly from ________ he had told the committee in private.", options:["which","what","that","how"], correct:1},
{text:"________ troubled the review panel most was the complete absence of any documentation to support the claims.", options:["What","That","Which","How"], correct:0},
{text:"She questioned ________ the proposed framework was genuinely capable of addressing the systemic issues.", options:["that","what","whether","which"], correct:2},
{text:"The fact ________ no formal complaint had been filed did not mean that the conduct was acceptable.", options:["which","that","what","of which"], correct:1},
{text:"He acknowledged ________ he should have escalated the matter to senior management at a much earlier stage.", options:["which","what","that","whether"], correct:2},
{text:"________ the decision proves controversial, the administration has prepared a detailed justification for public release.", options:["If","Whether","Although","Since"], correct:0},
{text:"The consultant advised the organisation to restructure ________ it could remain competitive in a changing market.", options:["in order that","so that","for","so as"], correct:1},
{text:"She revised the proposal three times ________ all objections raised during the initial review had been adequately addressed.", options:["until","while","unless","since"], correct:0},
{text:"The director spoke ________ she had full confidence in the outcome, despite the mounting evidence to the contrary.", options:["although","as if","in case","so that"], correct:1},
{text:"The longer the committee ________ on a resolution, the more divided its members become.", options:["deliberates","will deliberate","has deliberated","deliberated"], correct:0},
{text:"It was not ________ she reviewed the original agreement that she realised the extent of the discrepancy.", options:["when","until","after","before"], correct:1},
{text:"________ he said during the hearing was later contradicted by documentary evidence submitted to the court.", options:["What","That","Which","All what"], correct:0},
{text:"She found ________ impossible to remain neutral given the deeply personal nature of the allegations.", options:["this","that","it","which"], correct:2}
        ]
    }
}