export const hierarchy = {
  "Combined":{
    "Set 1" : [
{text:"CACOPHONY is to SOUND as STENCH is to ___", options:["Vision","Noise","Smell","Taste"], correct:2},
{text:"AUTHOR is to PLAGIARIZE as WITNESS is to ___", options:["Testify","Perjure","Observe","Report"], correct:1},
{text:"PEDIATRICIAN is to CHILD as GERONTOLOGIST is to ___", options:["Brain","Elderly","Heart","Sports"], correct:1},
{text:"EPHEMERAL is to PERMANENCE as TACITURN is to ___", options:["Verbosity","Silence","Patience","Wisdom"], correct:0},
{text:"ARCHIPELAGO is to ISLANDS as GALAXY is to ___", options:["Planets","Comets","Stars","Moons"], correct:2},
{text:"EMULATE is to ADMIRE as SATIRIZE is to ___", options:["Respect","Ridicule","Praise","Imitate"], correct:1},
// --- SYNONYMS (Q7–Q10) ---
{text:"Choose the word closest in meaning to OBFUSCATE.", options:["Clarify","Confuse","Simplify","Reveal"], correct:1},
{text:"Choose the word closest in meaning to LACONIC.", options:["Verbose","Lazy","Brief","Emotional"], correct:2},
{text:"Choose the word closest in meaning to PERFIDIOUS.", options:["Faithful","Treacherous","Cowardly","Generous"], correct:1},
{text:"Choose the word closest in meaning to INVETERATE.", options:["Habitual","Occasional","Temporary","Reluctant"], correct:0},
// --- ANTONYMS (Q11–Q14) ---
{text:"Choose the word most OPPOSITE in meaning to MAGNANIMOUS.", options:["Generous","Petty","Noble","Kind"], correct:1},
{text:"Choose the word most OPPOSITE in meaning to VERBOSE.", options:["Talkative","Eloquent","Laconic","Fluent"], correct:2},
{text:"Choose the word most OPPOSITE in meaning to LOQUACIOUS.", options:["Talkative","Taciturn","Cheerful","Energetic"], correct:1},
{text:"Choose the word most OPPOSITE in meaning to BENEVOLENT.", options:["Neutral","Kind","Malevolent","Apathetic"], correct:2},
// --- SENTENCE COMPLETION (Q15–Q18) ---
{text:"Despite being _____ for years, the scientist's theory was eventually vindicated by new evidence.", options:["celebrated","corroborated","derided","replicated"], correct:2},
{text:"The politician's speech was so _____ that even his opponents were moved by its eloquence.", options:["pedantic","banal","riveting","mundane"], correct:2},
{text:"Her _____ approach to negotiations — offering small concessions while retaining major advantages — proved highly effective.", options:["magnanimous","pusillanimous","Machiavellian","altruistic"], correct:2},
{text:"The documentary _____ the myth that sharks attack humans deliberately, showing that most attacks are cases of mistaken identity.", options:["perpetuates","corroborates","debunks","validates"], correct:2},
// --- SENTENCE CORRECTION (Q19–Q21) ---
{text:"Identify the grammatically correct version: 'If ___ you, I would reconsider the offer.'", options:["If I was you, I would reconsider","If I were you, I would reconsider","If I was you, I will reconsider","If I am you, I would reconsider"], correct:1},
{text:"Which sentence is grammatically correct regarding 'data'?", options:["The data clearly shows that inflation have risen","The data clearly show that inflation has risen","The data clearly shows that inflation has risen","The datum clearly shows that inflation has risen"], correct:1},
{text:"Choose the correct form: 'He _____ the money from the drawer.'", options:["denied to have stolen","denied having stolen","denied to steal","denied that he stolen"], correct:1},
// --- READING COMPREHENSION: Passage 1 (Q22–Q26) ---
// Passage: "The tragedy of the commons, popularized by Garrett Hardin in 1968, describes how individual users of a shared resource, acting in self-interest, deplete it through collective action. Each herder on an open pasture gains direct benefit from adding cattle while sharing the cost of overgrazing. Critics, notably Elinor Ostrom (Nobel Economics 2009), showed that communities can self-govern shared resources through defined boundaries, monitoring, graduated sanctions, and conflict resolution — without requiring privatization or government control."
{text:"[Passage 1] What is the primary purpose of the passage about the tragedy of the commons?", options:["To argue for privatization of all shared resources","To illustrate the conflict between individual and collective rationality","To critique Elinor Ostrom's Nobel Prize-winning work","To describe the history of ecological field research"], correct:1},
{text:"[Passage 1] According to Hardin's model, why does each herder add more cattle to a shared pasture?", options:["Because government regulations require it","Because the benefit is personal but the cost of overgrazing is shared","Because other herders pressure them to do so","Because the pasture has essentially unlimited capacity"], correct:1},
{text:"[Passage 1] Elinor Ostrom's research most directly challenged the assumption that:", options:["shared resources are necessarily finite and limited","privatization or government control are the only solutions to common resource problems","ecological research is irrelevant to economic theory","rational actors inevitably and always destroy shared resources"], correct:1},
{text:"[Passage 1] The word 'graduated' in the phrase 'graduated sanctions' most nearly means:", options:["academic or scholarly","increasing progressively in severity","sudden and absolute","rewarding compliance"], correct:1},
{text:"[Passage 1] Which finding would MOST undermine the passage's claim about community self-governance?", options:["Evidence that resource-use biases vary significantly across cultures","Research proving that communities invariably fail to self-govern shared resources without external authority","Studies showing Ostrom's methods work in some regions but not others","Data showing privatization reduces overuse in certain specific contexts"], correct:1},
// --- LOGICAL / ANALYTICAL REASONING (Q27–Q35) ---
{text:"All Blips are Blops. Some Blops are Blaps. Which of the following MUST be true?", options:["All Blips are Blaps","Some Blips are Blaps","No Blips are Blaps","None of the above must be true"], correct:3},
{text:"Five friends — Abebe, Bekele, Chala, Dina, Eba — sit in a row. Bekele sits between Abebe and Chala. Abebe is NOT adjacent to Chala. Dina sits at one end. Eba is adjacent to Dina. Which arrangement (left to right) is possible?", options:["Dina, Eba, Abebe, Bekele, Chala","Abebe, Chala, Bekele, Dina, Eba","Chala, Bekele, Abebe, Eba, Dina","Eba, Dina, Bekele, Abebe, Chala"], correct:0},
{text:"Three boxes are mislabeled: 'Teff', 'Wheat', and 'Mixed'. You pick one grain from the 'Mixed' box and it is Teff. What is the correct relabeling?", options:["Mixed→Teff, Teff→Wheat, Wheat→Mixed","Mixed→Wheat, Teff→Mixed, Wheat→Teff","Mixed→Teff, Wheat→Mixed, Teff→Wheat","Cannot be determined from one pick"], correct:2},
{text:"A clock shows exactly 3:15. What is the angle between the hour and minute hands?", options:["0°","7.5°","15°","22.5°"], correct:1},
{text:"B is the son of C, but C is NOT the mother of B. E is the sister of C. A is the mother of D. D is the granddaughter of C. How is B related to D?", options:["Father","Brother","Uncle","Cousin"], correct:2},
{text:"The average of A, B, C is 45. The average of C, D, E is 60. C = 30. What is the average of all five numbers A, B, C, D, E?", options:["50","54","57","60"], correct:2},
{text:"What comes next in the sequence? 2, 6, 12, 20, 30, ___", options:["40","42","44","36"], correct:1},
{text:"A is the father of B. B is the sister of C. D is the husband of C. E is the son of D and C. How is A related to E?", options:["Father","Uncle","Grandfather","Great-grandfather"], correct:2},
{text:"A man walks 5 km North, then turns East and walks 12 km. How far is he from his starting point?", options:["11 km","12 km","13 km","17 km"], correct:2},
// --- QUANTITATIVE REASONING (Q36–Q60) ---
{text:"If x + 1/x = 5, what is x² + 1/x²?", options:["20","23","25","27"], correct:1},
{text:"A sum of money doubles in 8 years at simple interest. In how many years will it triple?", options:["12","14","16","20"], correct:2},
{text:"The average of 5 consecutive even numbers is 26. What is the largest of these numbers?", options:["28","30","32","34"], correct:1},
{text:"A can do a job in 12 days, B in 18 days. After working together for 4 days, A leaves. How many MORE days does B need to finish?", options:["6","8","9","10"], correct:1},
{text:"If 3x − 2y = 7 and 2x + y = 7, find x + y.", options:["3","4","5","7"], correct:1},
{text:"A shopkeeper marks goods 40% above cost price and gives a 20% discount. What is the profit percentage?", options:["8%","10%","12%","20%"], correct:2},
{text:"What is the sum of all prime numbers strictly between 50 and 70?", options:["220","230","240","250"], correct:2},
{text:"A train 200 m long passes a stationary pole in 10 seconds. How long does it take to pass a platform 300 m long?", options:["20 s","25 s","30 s","35 s"], correct:1},
{text:"The area of a square is 144 cm². A rectangle has length equal to twice the side of the square and width equal to half the side. Find the rectangle's perimeter.", options:["48 cm","56 cm","60 cm","72 cm"], correct:2},
{text:"Pipe A fills a tank in 20 minutes, pipe B in 30 minutes, and pipe C drains it in 15 minutes. All three are open simultaneously. How long does it take to fill the empty tank?", options:["45 min","50 min","55 min","60 min"], correct:3},
{text:"In a class of 40 students, 25 passed Mathematics, 20 passed English, and 10 failed both subjects. How many students passed both?", options:["10","12","15","20"], correct:2},
{text:"If n! / (n − 2)! = 72, find the value of n.", options:["7","8","9","10"], correct:2},
{text:"The ratio of boys to girls in a school is 3:4. If there are 120 boys, what is the total number of students?", options:["240","260","280","320"], correct:2},
{text:"A rectangle has a diagonal of 10 cm and one side of 6 cm. Find its area.", options:["40 cm²","44 cm²","48 cm²","52 cm²"], correct:2},
{text:"What percentage of 3/8 is 1/4?", options:["50%","60%","66.67%","75%"], correct:2},
{text:"If log₂8 + log₃27 = x, find x.", options:["4","5","6","9"], correct:2},
{text:"A boat travels 30 km upstream in 3 hours and 30 km downstream in 2 hours. What is the speed of the current?", options:["2 km/h","2.5 km/h","3 km/h","5 km/h"], correct:1},
{text:"In how many ways can 4 books be arranged on a shelf if 2 specific books must always be placed together?", options:["6","12","24","48"], correct:1},
{text:"The sum of the first n natural numbers is 210. Find n.", options:["18","19","20","21"], correct:2},
{text:"A circle has a circumference of 44 cm. Find its area. (Use π = 22/7)", options:["132 cm²","144 cm²","154 cm²","176 cm²"], correct:2},
{text:"If 2^x = 32, what is the value of 2^(x+3)?", options:["128","192","256","512"], correct:2},
{text:"The price of an item is reduced by 20%. By what percentage must it now be increased to restore the original price?", options:["20%","22%","25%","30%"], correct:2},
{text:"Find the LCM of 12, 18, and 24.", options:["48","60","72","144"], correct:2},
{text:"The angles of a triangle are in the ratio 2:3:4. What is the measure of the largest angle?", options:["60°","70°","80°","90°"], correct:2},
{text:"A number is increased by 20% and then decreased by 20%. What is the net percentage change?", options:["0% change","2% decrease","4% decrease","6% decrease"], correct:2},

    ],
    "Set 2" : [
        // --- ANALOGIES (Q61–Q66) ---
{text:"MYOPIA is to SPECTACLES as DEAFNESS is to ___", options:["Audiologist","Hearing Aid","Medicine","Surgery"], correct:1},
{text:"CHOREOGRAPHY is to DANCE as LIBRETTO is to ___", options:["Music","Ballet","Opera","Film"], correct:2},
{text:"TEMERITY is to CAUTION as PARSIMONY is to ___", options:["Thrift","Generosity","Wealth","Economy"], correct:1},
{text:"CARTOGRAPHER is to MAPS as LEXICOGRAPHER is to ___", options:["Books","Laws","Dictionaries","Libraries"], correct:2},
{text:"EPHEMERAL is to TRANSIENT as OBSTINATE is to ___", options:["Flexible","Stubborn","Decisive","Timid"], correct:1},
{text:"ARCHITECT is to BLUEPRINT as COMPOSER is to ___", options:["Symphony","Score","Notes","Melody"], correct:1},
// --- SYNONYMS (Q67–Q70) ---
{text:"Choose the word closest in meaning to QUERULOUS.", options:["Quiet","Complaining","Quick","Curious"], correct:1},
{text:"Choose the word closest in meaning to RECONDITE.", options:["Obscure","Common","Recovered","Colorful"], correct:0},
{text:"Choose the word closest in meaning to AMELIORATE.", options:["Worsen","Improve","Maintain","Assess"], correct:1},
{text:"Choose the word closest in meaning to PUGNACIOUS.", options:["Peaceful","Fearful","Combative","Cowardly"], correct:2},
// --- ANTONYMS (Q71–Q74) ---
{text:"Choose the word most OPPOSITE in meaning to EBULLIENCE.", options:["Gloom","Excitement","Joy","Energy"], correct:0},
{text:"Choose the word most OPPOSITE in meaning to PERSPICACIOUS.", options:["Wise","Clever","Obtuse","Sharp"], correct:2},
{text:"Choose the word most OPPOSITE in meaning to INTREPID.", options:["Brave","Bold","Timid","Reckless"], correct:2},
{text:"Choose the word most OPPOSITE in meaning to PROFLIGATE.", options:["Wasteful","Thrifty","Rich","Corrupt"], correct:1},
// --- SENTENCE COMPLETION (Q75–Q78) ---
{text:"The scientist's findings were so _____ that even seasoned researchers struggled to grasp their full implications.", options:["mundane","abstruse","redundant","lucid"], correct:1},
{text:"Far from being _____, the ancient ruins were remarkably well-preserved, suggesting a sophisticated maintenance system.", options:["pristine","dilapidated","elaborate","monumental"], correct:1},
{text:"The CEO's decision to _____ the merger, despite intense pressure from the board, ultimately saved the company from collapse.", options:["hasten","approve","rescind","broadcast"], correct:2},
{text:"Renowned for her _____, the professor could explain even the most complex quantum phenomena in terms a child could grasp.", options:["pedantry","obfuscation","didactic complexity","perspicuity"], correct:3},
// --- SENTENCE CORRECTION (Q79–Q81) ---
{text:"Choose the grammatically correct version of: 'She insisted that he _____ to the meeting without fail.'", options:["insisted that he comes to the meeting","insisted that he come to the meeting","insisted that he will come to the meeting","insisted that he had come to the meeting"], correct:1},
{text:"Choose the grammatically correct version: 'He has been working on this project _____ three months.'", options:["been working on this project since three months","been working on this project for three months","is working on this project since three months","worked on this project since three months"], correct:1},
{text:"Choose the grammatically correct version: 'The number of applicants _____ dramatically this year.'", options:["number of applicants for the position have increased","number of applicants for the position has increased","number of applicants for the position were increased","numbers of applicants for the position has increased"], correct:1},
// --- READING COMPREHENSION: Passage 2 (Q82–Q86) ---
// Passage: "Cognitive biases are systematic patterns of deviation from rationality in judgment. Unlike random errors, biases follow predictable patterns. The anchoring effect causes individuals to rely too heavily on the first piece of information encountered — in a classic experiment, participants' estimates of African nations in the UN were heavily skewed by an arbitrary number from a spinning wheel. Confirmation bias, perhaps the most pervasive, causes people to seek and favor information confirming preexisting beliefs while ignoring contradictory evidence. Crucially, awareness of cognitive biases does not necessarily make an individual immune to them — even experts who study biases are subject to them."
{text:"[Passage 2] What is the primary focus of the passage about cognitive biases?", options:["A comparison of psychological research methodologies","Why humans make poor decisions in all contexts","Cognitive biases as predictable, systematic errors in judgment","The history of Tversky and Kahneman's collaboration"], correct:2},
{text:"[Passage 2] Which bias does the spinning wheel experiment most directly illustrate?", options:["Confirmation bias","The anchoring effect","Negativity bias","The availability heuristic"], correct:1},
{text:"[Passage 2] What is most strongly implied by the passage's final sentence?", options:["Only untrained individuals are subject to cognitive biases","Expertise fully protects against cognitive biases","Cognitive biases are extremely rare in everyday thinking","Knowing about a bias does not guarantee immunity from it"], correct:3},
{text:"[Passage 2] The word 'pervasive' as used in the passage most nearly means:", options:["Harmful","Widespread","Subtle","Complex"], correct:1},
{text:"[Passage 2] Which finding would MOST weaken the central argument of the passage?", options:["Evidence that biases vary significantly across cultural groups","Research proving that sustained awareness training can fully eliminate cognitive biases","Studies showing confirmation bias affects more people than anchoring","Findings that cognitive biases are more pronounced in high-stress situations"], correct:1},
// --- LOGICAL / ANALYTICAL REASONING (Q87–Q95) ---
{text:"Six people — A, B, C, D, E, F — sit around a circular table. A is directly opposite D. B is not adjacent to D. C is adjacent to A. E sits between B and F. Who sits directly opposite B?", options:["A","C","E","F"], correct:3},
{text:"In a code: FRIEND = HUMJTK (each letter shifted by 2, 3, 4, 5, 6, 7 respectively). Using the same rule, how is CANDLE coded?", options:["EDRIRL","EFRIRL","ECRIML","EDRIML"], correct:0},
{text:"Cities A, B, C form a triangle: A is 8 km from B, B is 15 km from C, and A is 17 km from C. What type of triangle is formed?", options:["Equilateral","Isosceles","Obtuse-angled","Right-angled"], correct:3},
{text:"In a class, 2/5 of students play football, 1/3 play basketball, and 1/6 play both. What fraction plays neither sport?", options:["1/5","7/30","13/30","11/30"], correct:2},
{text:"A man looks at a photograph and says, 'Brothers and sisters I have none, but this man's father is my father's son.' Who is in the photograph?", options:["Himself","His father","His son","His brother"], correct:2},
{text:"What letter comes next in this sequence? J, F, M, A, M, J, J, ___", options:["S","A","J","O"], correct:1},
{text:"Five students A–E are ranked (no ties). A ranks above C. D ranks above B. E is ranked 3rd. B ranks above A. What is the correct ranking from 1st to 5th?", options:["D, B, E, A, C","D, E, B, A, C","B, D, E, A, C","D, B, A, E, C"], correct:0},
{text:"The sum of the current ages of a father and son is 56. Four years ago, the father was 3 times as old as the son. Find the son's current age.", options:["14","16","18","20"], correct:1},
{text:"A survey of 100 households shows: 60 have a TV, 45 have a Radio, and 30 have both. How many households have at least one of the two?", options:["65","70","75","80"], correct:2},
// --- QUANTITATIVE REASONING (Q96–Q120) ---
{text:"The sum of three consecutive odd numbers is 81. What is the middle number?", options:["25","27","29","31"], correct:1},
{text:"In a right triangle, if sin(x) = 3/5, what is cos(x)?", options:["3/4","4/5","5/3","1/2"], correct:1},
{text:"Find the HCF (Highest Common Factor) of 36 and 54.", options:["9","12","18","27"], correct:2},
{text:"A rectangle's length is increased by 25% and its width is decreased by 20%. What is the net percentage change in the area?", options:["5% increase","5% decrease","0% change","10% decrease"], correct:2},
{text:"If a:b = 2:3 and b:c = 4:5, find a:c.", options:["2:5","8:15","4:15","6:10"], correct:1},
{text:"A car travels 60 km at 40 km/h. At what speed must it travel the next 60 km to achieve an overall average speed of 60 km/h?", options:["80 km/h","100 km/h","120 km/h","90 km/h"], correct:2},
{text:"What is 30% of 40% of 500?", options:["40","50","60","70"], correct:2},
{text:"In how many distinct ways can the letters of the word LEVEL be arranged?", options:["20","30","60","120"], correct:1},
{text:"The compound interest on a principal for 2 years at 10% per annum is 420 Birr. Find the principal.", options:["1500 Birr","1800 Birr","2000 Birr","2100 Birr"], correct:2},
{text:"A bag contains 4 red and 3 blue balls. If 2 balls are drawn at random, what is the probability that one is red and one is blue?", options:["3/7","4/7","12/49","2/7"], correct:1},
{text:"The angles of a quadrilateral are in the ratio 1:2:3:4. What is the measure of the largest angle?", options:["120°","135°","144°","150°"], correct:2},
{text:"A shopkeeper buys 100 items at 50 Birr each. He sells 80 at 65 Birr each and 20 at 40 Birr each. What is the total profit?", options:["500 Birr","800 Birr","1000 Birr","1200 Birr"], correct:2},
{text:"Solve for all values of x: |2x − 5| = 9", options:["x = 7 only","x = −2 only","x = 7 or x = −2","x = 2 or x = −7"], correct:2},
{text:"The total surface area of a cube is 96 cm². Find its volume.", options:["48 cm³","56 cm³","64 cm³","72 cm³"], correct:2},
{text:"What is 0.1% of 500?", options:["0.05","0.5","5","50"], correct:1},
{text:"If x:y = 3:4 and y:z = 8:9, find x:z.", options:["1:3","2:3","3:4","4:9"], correct:1},
{text:"The perimeter of an equilateral triangle is 36 cm. Find its area.", options:["36√3 cm²","48√3 cm²","72√3 cm²","36 cm²"], correct:0},
{text:"What is the next term in the sequence? 1, 4, 9, 16, 25, ___", options:["30","35","36","49"], correct:2},
{text:"A student's scores on five tests are 65, 72, 80, 58, and x. If the average is 70, find x.", options:["70","72","75","78"], correct:2},
{text:"Two numbers are in the ratio 5:8. Their sum is 156. What is the larger number?", options:["60","80","96","100"], correct:2},
{text:"A and B start from the same point and run in opposite directions. A runs at 10 km/h and B at 8 km/h. After how many hours will they be 45 km apart?", options:["2 h","2.5 h","3 h","3.5 h"], correct:1},
{text:"Find x if 5^x = 625.", options:["3","4","5","6"], correct:1},
{text:"A right triangle has legs of length 7 cm and 24 cm. Find the hypotenuse.", options:["20 cm","23 cm","25 cm","28 cm"], correct:2},
{text:"Find the mode of the data set: 3, 7, 2, 7, 5, 3, 7, 1.", options:["3","5","7","2"], correct:2},
{text:"A man earns 8,000 Birr per month. He spends 30% on rent and 25% on food. How much does he save monthly?", options:["2,400 Birr","3,200 Birr","3,600 Birr","4,000 Birr"], correct:2},


    ],
    "Set 3" : [
{text:"BIBLIOGRAPHY is to BOOKS as DISCOGRAPHY is to ___", options:["Paintings","Recordings","Films","Exhibitions"], correct:1},
{text:"SCALPEL is to SURGEON as GAVEL is to ___", options:["Carpenter","Auctioneer","Police Officer","Politician"], correct:1},
{text:"BENIGN is to MALIGNANT as TRANSPARENT is to ___", options:["Clear","Sheer","Opaque","Glassy"], correct:2},
{text:"ETYMOLOGY is to WORDS as ORNITHOLOGY is to ___", options:["Plants","Insects","Birds","Stars"], correct:2},
{text:"PROFUSE is to MEAGER as SERENE is to ___", options:["Peaceful","Turbulent","Calm","Quiet"], correct:1},
{text:"LIBEL is to WRITTEN as SLANDER is to ___", options:["Printed","Verbal","False","Legal"], correct:1},
// --- SYNONYMS (Q127–Q130) ---
{text:"Choose the word closest in meaning to INIMICAL.", options:["Hostile","Friendly","Similar","Identical"], correct:0},
{text:"Choose the word closest in meaning to SOPORIFIC.", options:["Exciting","Energizing","Sleep-inducing","Depressing"], correct:2},
{text:"Choose the word closest in meaning to DILETTANTE.", options:["Professional","Amateur","Expert","Scholar"], correct:1},
{text:"Choose the word closest in meaning to PELLUCID.", options:["Muddy","Translucent","Dark","Dense"], correct:1},
// --- ANTONYMS (Q131–Q134) ---
{text:"Choose the word most OPPOSITE in meaning to SANGUINE.", options:["Cheerful","Hopeful","Pessimistic","Excited"], correct:2},
{text:"Choose the word most OPPOSITE in meaning to ACRIMONY.", options:["Bitterness","Cordiality","Anger","Contempt"], correct:1},
{text:"Choose the word most OPPOSITE in meaning to PEDANTIC.", options:["Scholarly","Precise","Casual","Detailed"], correct:2},
{text:"Choose the word most OPPOSITE in meaning to INSCRUTABLE.", options:["Mysterious","Hidden","Obvious","Complex"], correct:2},
// --- SENTENCE COMPLETION (Q135–Q138) ---
{text:"The mayor's _____ response to the flood victims was widely criticized as inadequate and tone-deaf.", options:["empathetic","perfunctory","generous","immediate"], correct:1},
{text:"Her research _____ the long-held belief that the site was uninhabited, revealing instead a complex ancient settlement.", options:["confirmed","supported","undermined","documented"], correct:2},
{text:"Renowned for her _____, the professor could explain even the most complex quantum phenomena in terms a child could understand.", options:["pedantry","obfuscation","didactic complexity","perspicuity"], correct:3},
{text:"The treaty, far from ending the hostilities, merely _____ tensions that eventually erupted into full-scale war.", options:["resolved","eliminated","exacerbated","transformed"], correct:2},
// --- SENTENCE CORRECTION (Q139–Q141) ---
{text:"Choose the grammatically correct version: 'Each of the students in the class _____ submitted _____ assignment on time.'", options:["Each of the students in the class have submitted their assignments","Each of the students in the class has submitted his or her assignment","Each of the students in the class has submitted their assignments","Each students in the class have submitted their assignment"], correct:1},
{text:"Choose the grammatically correct version involving 'because' vs 'due to':", options:["The meeting was postponed due to many members were absent","The meeting was postponed because many members were absent","The meeting was postponed due to many members is absent","The meeting was postponed due to the absent of many members"], correct:1},
{text:"Choose the grammatically correct version: 'He is one of those students who always _____ homework on time.'", options:["one of those students who always does his homework","one of those students who always do their homework","one of those student who always does his homework","one of those students who always done his homework"], correct:1},
// --- READING COMPREHENSION: Passage 3 (Q142–Q146) ---
// Passage: "The Green Revolution of the 1960s–70s dramatically increased agricultural yields in developing countries through high-yielding crop varieties, synthetic fertilizers, and pesticides, averting widespread famine. However, intensive monoculture led to significant biodiversity loss as thousands of traditional varieties were abandoned. Chemical inputs contaminated water and degraded soil. Economic benefits were unevenly distributed: wealthier farms could afford the new inputs while smaller subsistence farmers were often displaced. Critics argue the Revolution, while buying time, may have created 'structural vulnerability' — a global food system dependent on a narrow genetic base and expensive external inputs."
{text:"[Passage 3] The author's attitude toward the Green Revolution is best described as:", options:["Wholly positive, citing food security gains","Wholly negative, citing environmental damage","Balanced, acknowledging both significant benefits and complex drawbacks","Indifferent, presenting only neutral facts"], correct:2},
{text:"[Passage 3] Which of the following was NOT cited in the passage as a negative consequence of the Green Revolution?", options:["Soil degradation from heavy chemical use","Prevention of widespread famine in developing countries","Loss of traditional crop variety biodiversity","Unequal distribution of economic benefits among farmers"], correct:1},
{text:"[Passage 3] The phrase 'structural vulnerability' in the passage refers to:", options:["Weak physical agricultural infrastructure in developing nations","Fragility created by dependence on a narrow genetic crop base and expensive external inputs","The psychological impact of past famines on farming populations","Economic inequality between large commercial and small subsistence farms"], correct:1},
{text:"[Passage 3] Which concern does the author most strongly imply for the future?", options:["Synthetic fertilizers will be depleted within decades","High-yield crop varieties will soon stop producing sufficient yields","The global food system may be dangerously fragile due to limited crop genetic diversity","Wealthier farms will eventually monopolize all food production globally"], correct:2},
{text:"[Passage 3] The word 'monoculture' as used in the passage most likely refers to:", options:["A diet consisting of only one type of food","A cultural system that enforces ideological uniformity","The practice of cultivating a single crop species over a large area","A form of agrarian governance common in developing nations"], correct:2},
// --- LOGICAL / ANALYTICAL REASONING (Q147–Q155) ---
{text:"All squares are rectangles. Some rectangles are rhombuses. No rhombus is a circle. Which statement can be definitively concluded?", options:["All squares are rhombuses","Some squares are circles","No square is a rhombus","None of the above can be definitively concluded from these premises alone"], correct:3},
{text:"In a code: TIGER = 52317 and GIRL = 3271. Using these values, what is the code for GRIT?", options:["3725","3572","7325","2735"], correct:0},
{text:"Water flows into an empty 200-liter tank at 6 liters/min while leaking out at 2 liters/min. What fraction of the tank is full after exactly 30 minutes?", options:["1/2","3/5","2/3","4/5"], correct:1},
{text:"A large equilateral triangle is divided into 4 smaller equilateral triangles by connecting the midpoints of its sides. How many triangles of ALL sizes are visible in the figure?", options:["4","5","6","8"], correct:1},
{text:"A merchant mixes coffee costing 80 Birr/kg with coffee costing 120 Birr/kg to produce a blend worth 96 Birr/kg. In what ratio (cheap:expensive) must they be mixed?", options:["1:2","2:3","3:2","4:3"], correct:2},
{text:"P is the son of Q. Q is the brother of R. R is the daughter of S. T is the husband of S. How is T related to P?", options:["Father","Uncle","Grandfather","Great-grandfather"], correct:2},
{text:"What is the smallest number that leaves a remainder of 2 when divided by 4, 5, or 6?", options:["22","42","62","122"], correct:2},
{text:"Three workers can complete a job in 6, 8, and 12 days respectively. Working together, how long will the job take?", options:["2 days","2⅔ days","3 days","3⅓ days"], correct:1},
{text:"What comes next in the sequence? 1, 1, 2, 3, 5, 8, 13, ___", options:["18","20","21","23"], correct:2},
// --- QUANTITATIVE REASONING (Q156–Q180) ---
{text:"If 3^(x+1) = 81, find the value of x.", options:["2","3","4","5"], correct:1},
{text:"Find the median of the data set: 12, 7, 3, 14, 6, 11, 9, 15, 8.", options:["8","9","10","11"], correct:1},
{text:"A factory produces 1,200 items in 8 hours using 5 machines. How many hours will 8 machines take to produce 1,800 items?", options:["6 h","7 h","7.5 h","8 h"], correct:2},
{text:"What is 2^10 ÷ 2^7?", options:["4","6","8","16"], correct:2},
{text:"A bank offers 12% per annum simple interest. How much interest is earned on 5,000 Birr over 2.5 years?", options:["1,000 Birr","1,200 Birr","1,500 Birr","1,800 Birr"], correct:2},
{text:"Two numbers have HCF = 12 and LCM = 144. If one number is 36, what is the other?", options:["36","42","48","60"], correct:2},
{text:"A car travels at 90 km/h and a truck at 60 km/h, both heading to a city 360 km away from the same starting point at the same time. How many hours earlier does the car arrive?", options:["1 h","1.5 h","2 h","2.5 h"], correct:2},
{text:"What is the probability of rolling a prime number on a standard 6-sided die?", options:["1/3","1/2","2/3","5/6"], correct:1},
{text:"The perimeter of a square equals the circumference of a circle with radius 7 cm. Find the area of the square. (Use π = 22/7)", options:["100 cm²","121 cm²","144 cm²","169 cm²"], correct:1},
{text:"Simplify: (a² − b²) / (a + b)", options:["a + b","a − b","a² − b","2a"], correct:1},
{text:"A 60-liter mixture contains milk and water in the ratio 2:1. How much water must be added to make the ratio 1:1?", options:["10 L","15 L","20 L","25 L"], correct:2},
{text:"A square's diagonal is doubled in length. By what factor does the square's area increase?", options:["2","3","4","8"], correct:2},
{text:"The average of 10 numbers is 25. One number was incorrectly recorded as 17 instead of the correct value 71. What is the correct average?", options:["28.4","29","30.4","32"], correct:2},
{text:"If p and q are the roots of x² − 5x + 6 = 0, find the value of p² + q².", options:["11","13","15","25"], correct:1},
{text:"What is the value of 111 × 111?", options:["11111","12211","12321","12421"], correct:2},
{text:"A telephone pole casts a shadow of 12 m when a vertical 2 m stick casts a shadow of 3 m at the same time. How tall is the pole?", options:["6 m","8 m","9 m","10 m"], correct:1},
{text:"A 20% salt solution is mixed with a 30% salt solution in the ratio 3:2. What is the salt concentration of the resulting mixture?", options:["22%","24%","25%","26%"], correct:1},
{text:"In an arithmetic progression (AP), the first term is 3 and the common difference is 4. What is the 10th term?", options:["35","37","39","41"], correct:2},
{text:"A room measures 8 m × 5 m × 3 m. How many cubic meters of air does it contain?", options:["100","110","120","130"], correct:2},
{text:"If f(x) = 2x² − 3x + 1, find f(3).", options:["8","9","10","11"], correct:2},
{text:"A convex polygon has 9 sides. How many diagonals does it have?", options:["18","21","24","27"], correct:3},
{text:"The price of petrol rises by 25%. By what percentage must a motorist reduce fuel consumption to keep the total fuel expenditure unchanged?", options:["15%","20%","25%","30%"], correct:1},
{text:"How many times does the digit '1' appear in all integers from 1 to 100 inclusive?", options:["19","20","21","22"], correct:1},
{text:"What is the value of √0.0625?", options:["0.025","0.25","0.5","2.5"], correct:1},
{text:"A number gives remainder 3 when divided by 5, and remainder 4 when divided by 7. What is the smallest positive such number?", options:["13","18","23","33"], correct:1},

    ]
  }    
}